//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MidasIAPExternalReporterProtocol-Protocol.h"

@class NSString;
@protocol MidasIAPRuntimeDelegate;

@interface APMidasExternalReporterAdapater : NSObject <MidasIAPExternalReporterProtocol>
{
    id <MidasIAPRuntimeDelegate> _runtimeDelegate;
}

@property(nonatomic) __weak id <MidasIAPRuntimeDelegate> runtimeDelegate; // @synthesize runtimeDelegate=_runtimeDelegate;
- (void).cxx_destruct;
- (id)_convertReport2Event:(id)arg1;
- (void)insert:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

