//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ASAuthorizationControllerDelegate-Protocol.h"
#import "ASAuthorizationControllerPresentationContextProviding-Protocol.h"

@class ASAuthorizationAppleIDCredential, NSString;
@protocol AppleIDBindLogicDelegate;

@interface AppleIDBindLogic : NSObject <ASAuthorizationControllerDelegate, ASAuthorizationControllerPresentationContextProviding>
{
    id <AppleIDBindLogicDelegate> _delegate;
    ASAuthorizationAppleIDCredential *_appleIDCredential;
}

+ (_Bool)isAppleIDBound;
- (void).cxx_destruct;
@property(retain, nonatomic) ASAuthorizationAppleIDCredential *appleIDCredential; // @synthesize appleIDCredential=_appleIDCredential;
@property(nonatomic) __weak id <AppleIDBindLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (id)generateAppleIDErrorFromError:(id)arg1 andResponse:(id)arg2;
- (void)callAppleIDAuthorizeFailDelegateWithError:(id)arg1 andResponse:(id)arg2;
- (void)appleIDAuthorizeWithIDCRedirectCount:(unsigned long long)arg1;
- (void)appleIDAuthorize;
- (void)updateAppleIDBindStatusInSetting:(_Bool)arg1;
- (void)unbindAppleID;
- (void)bindAppleID;
- (id)presentationAnchorForAuthorizationController:(id)arg1;
- (void)authorizationController:(id)arg1 didCompleteWithError:(id)arg2;
- (void)authorizationController:(id)arg1 didCompleteWithAuthorization:(id)arg2;
@property(readonly, nonatomic) _Bool authorizedFromAppleSucceed;
- (void)requestAuthorizeFromApple;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

