//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface AppPatMessageRefreshContext : NSObject
{
    _Bool _useLightStyle;
    _Bool _useLink;
    _Bool _needCleanRefresh;
    double _width;
    NSMutableDictionary *_contentIdToTimeOffset;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *contentIdToTimeOffset; // @synthesize contentIdToTimeOffset=_contentIdToTimeOffset;
@property(nonatomic) _Bool needCleanRefresh; // @synthesize needCleanRefresh=_needCleanRefresh;
@property(nonatomic) _Bool useLink; // @synthesize useLink=_useLink;
@property(nonatomic) _Bool useLightStyle; // @synthesize useLightStyle=_useLightStyle;
@property(nonatomic) double width; // @synthesize width=_width;
- (void)updateNeedCleanRefreshWithContext:(id)arg1;
- (id)init;

@end

