//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AudioFileTransferInfo;

@interface AudioFileTransferTask : NSObject
{
    AudioFileTransferInfo *_info;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AudioFileTransferInfo *info; // @synthesize info=_info;
- (id)promiseTransferedFile;
- (id)initWithInfo:(id)arg1;

@end

