//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

#import "BrandProfileFuwuBaseViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UIButton, UILabel, UIScrollView, UIView;
@protocol BrandProfileFuwuContainerViewDelegate;

@interface BrandProfileFuwuContainerView : MMUIView <BrandProfileFuwuBaseViewDelegate>
{
    double _maxContainerHeight;
    UIScrollView *_fuwuScrollView;
    UILabel *_topLabel;
    UIView *_topLabelDividingView;
    NSMutableArray *_fuwuViewList;
    UIView *_bottomDividingView;
    UIButton *_cancelButton;
    id <BrandProfileFuwuContainerViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <BrandProfileFuwuContainerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIView *bottomDividingView; // @synthesize bottomDividingView=_bottomDividingView;
@property(retain, nonatomic) NSMutableArray *fuwuViewList; // @synthesize fuwuViewList=_fuwuViewList;
@property(retain, nonatomic) UIView *topLabelDividingView; // @synthesize topLabelDividingView=_topLabelDividingView;
@property(retain, nonatomic) UILabel *topLabel; // @synthesize topLabel=_topLabel;
@property(retain, nonatomic) UIScrollView *fuwuScrollView; // @synthesize fuwuScrollView=_fuwuScrollView;
@property(nonatomic) double maxContainerHeight; // @synthesize maxContainerHeight=_maxContainerHeight;
- (void)onFuwuInfoClicked:(id)arg1;
- (void)onCancelBtnClicked;
- (void)reCreateRoundCornersLayer;
- (double)calcuateCancelButtonHeight;
- (void)layoutSubviews;
- (void)removeFuwuViewList;
- (void)setFuwuInfoList:(id)arg1;
- (void)setDisplayName:(id)arg1;
- (void)setupSubviews;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

