//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BrandNotificationCellViewModel.h"

@class BrandNewXMLNotification, NSString;

@interface BrandNewXmlNotificationCellViewModel : BrandNotificationCellViewModel
{
    BrandNewXMLNotification *_notification;
}

+ (_Bool)canCreateViewModelWithMsgWrap:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) BrandNewXMLNotification *notification; // @synthesize notification=_notification;
@property(readonly, nonatomic) NSString *webPageUrl;
- (id)messageText;
- (id)brandContact;
- (void)internalInitWithMsg:(id)arg1;
- (id)initWithMessage:(id)arg1 viewWidth:(double)arg2;
- (id)cellViewClassName;

@end

