//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UISwitch;

@interface DiscoverEntranceSetSwitchInfo : NSObject
{
    _Bool _isOn;
    NSString *_title;
    NSString *_desc;
    unsigned long long _type;
    UISwitch *_uiSwitch;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UISwitch *uiSwitch; // @synthesize uiSwitch=_uiSwitch;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) _Bool isOn; // @synthesize isOn=_isOn;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;

@end

