//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class WCTDatabase;

@interface EdgeComputingWCDBManager : MMObject
{
    WCTDatabase *edgeDatabase;
}

- (void).cxx_destruct;
- (unsigned long long)queryRowNum:(id)arg1;
- (id)querySQL:(id)arg1;
- (_Bool)execuSQL:(id)arg1;
- (void)close;
- (void)dealloc;
- (id)init:(id)arg1;

@end

