//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@interface EdgeComputingMonitor : MMObject
{
}

+ (_Bool)isMonitorOpen;
+ (void)statRealReportProcess:(unsigned int)arg1;
+ (void)statRejectDataLimit:(id)arg1 withAmount:(unsigned long long)arg2;
+ (void)statStorageAmount:(id)arg1 withAmount:(unsigned long long)arg2;
+ (void)statScriptDownloadSuccess:(_Bool)arg1;
+ (void)statSqlConfigParseError:(_Bool)arg1;
+ (void)statScriptConfigParseError:(_Bool)arg1;
+ (void)statJsApiCostTime:(id)arg1 withCostTime:(unsigned long long)arg2 withType:(unsigned long long)arg3;
+ (void)statInstantWorkTime:(unsigned long long)arg1 withDataSzie:(unsigned long long)arg2;
+ (void)statSingleScriptWorkTime:(id)arg1 withCostTime:(unsigned long long)arg2 withDataSzie:(unsigned long long)arg3;
+ (void)statRegularSqlWorkTime:(unsigned long long)arg1 withDataSzie:(unsigned long long)arg2;
+ (void)statRegularScriptWorkTime:(unsigned long long)arg1 withDataSzie:(unsigned long long)arg2;
+ (void)statRegularWorkTime:(unsigned long long)arg1 withDataSzie:(unsigned long long)arg2;
+ (void)statSQLQueryCostTime:(id)arg1 withCostTime:(unsigned long long)arg2 withDataSzie:(unsigned long long)arg3;
+ (void)statStorageCostTime:(id)arg1 withCostTime:(unsigned long long)arg2 withDataSzie:(unsigned long long)arg3;
+ (void)statCacheCostTime:(id)arg1 withCostTime:(unsigned long long)arg2 withDataSzie:(unsigned long long)arg3;
+ (void)statComputingCostTime:(id)arg1 withCostTime:(unsigned long long)arg2 withDataSzie:(unsigned long long)arg3;
+ (void)monitorProcess:(id)arg1 withProcess:(unsigned int)arg2 withReportTimeEC:(unsigned long long)arg3;

@end

