//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FaceRecogFlashUtil : NSObject
{
}

+ (id)addBlurEffectToImage:(id)arg1 withEdgeClamp:(_Bool)arg2;
+ (id)addBlurEffectToImage:(id)arg1;
+ (long long)convertToYtAction:(unsigned long long)arg1;
+ (id)decryptData:(id)arg1 withKey:(id)arg2;
+ (id)encryptData:(id)arg1 withKey:(id)arg2;
+ (id)insertVerifyDataToImage:(id)arg1 lipReadingData:(id)arg2 bioId:(id)arg3;

@end

