//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "IFTSFavMgrExt-Protocol.h"

@class FavoritesItemDB, FavoritesSearchDB, NSString;

@interface FavoritesSearchMgr : MMObject <IFTSFavMgrExt>
{
    FavoritesItemDB *_favItemDB;
    FavoritesSearchDB *_favSearchDB;
}

- (void).cxx_destruct;
- (void)onFTSFavResultChanged:(id)arg1;
- (id)syncSearch:(id)arg1 byType:(int)arg2 tags:(id)arg3;
- (void)deleteFirstContent:(id)arg1 inSring:(id)arg2;
- (void)deleteAccountInfo:(id)arg1 inSearchString:(id)arg2;
- (_Bool)checkErrorMatchContentIn:(id)arg1 withFavItem:(id)arg2 bySearchContent:(id)arg3;
- (void)asyncSearch:(id)arg1 byType:(int)arg2 tags:(id)arg3 taskKey:(id)arg4;
- (void)cancelSearch:(id)arg1;
- (void)loadMoreSearchContent:(id)arg1;
- (_Bool)hasSearchDoneForTaskKey:(id)arg1 searchContent:(id)arg2;
- (id)getSearchKeyword:(id)arg1;
- (id)genSearchTaskKey;
- (_Bool)deleteSearchInfoByLocalFavId:(unsigned int)arg1;
- (_Bool)insertOrUpdateSearchInfoForItem:(id)arg1;
- (void)initDB:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

