//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseRequest, FinderBaseRequest, NSData, NSString;

@interface FinderGetMsgSessionIdRequest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;
@property(retain, nonatomic) FinderBaseRequest *finderBasereq; // @dynamic finderBasereq;
@property(retain, nonatomic) NSData *liveContactExtInfo; // @dynamic liveContactExtInfo;
@property(nonatomic) unsigned int myAccountType; // @dynamic myAccountType;
@property(retain, nonatomic) NSString *myAccountUsername; // @dynamic myAccountUsername;
@property(nonatomic) unsigned int sourceType; // @dynamic sourceType;
@property(nonatomic) _Bool supportAlias; // @dynamic supportAlias;
@property(nonatomic) unsigned long long toCommentId; // @dynamic toCommentId;
@property(retain, nonatomic) NSString *toFansId; // @dynamic toFansId;
@property(nonatomic) unsigned long long toLikeId; // @dynamic toLikeId;
@property(retain, nonatomic) NSString *toLotteryId; // @dynamic toLotteryId;
@property(nonatomic) unsigned long long toObjectId; // @dynamic toObjectId;
@property(retain, nonatomic) NSString *toUsername; // @dynamic toUsername;

@end

