//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderLiveShopWindowProductItem_ProductPage, NSString;

@interface FinderLiveShopWindowProductItem : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *appUsername; // @dynamic appUsername;
@property(retain, nonatomic) NSString *extBuff; // @dynamic extBuff;
@property(retain, nonatomic) NSString *extraData; // @dynamic extraData;
@property(retain, nonatomic) NSString *imgUrl; // @dynamic imgUrl;
@property(nonatomic) unsigned int maxPrice; // @dynamic maxPrice;
@property(nonatomic) unsigned int minPrice; // @dynamic minPrice;
@property(nonatomic) unsigned int platformId; // @dynamic platformId;
@property(retain, nonatomic) NSString *platformName; // @dynamic platformName;
@property(nonatomic) unsigned long long productId; // @dynamic productId;
@property(retain, nonatomic) FinderLiveShopWindowProductItem_ProductPage *productPage; // @dynamic productPage;
@property(nonatomic) unsigned int promoting; // @dynamic promoting;
@property(retain, nonatomic) NSString *shopExtraData; // @dynamic shopExtraData;
@property(nonatomic) unsigned int status; // @dynamic status;
@property(nonatomic) unsigned int stock; // @dynamic stock;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) FinderLiveShopWindowProductItem_ProductPage *userPurchasePage; // @dynamic userPurchasePage;

@end

