//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface ForeignHbDetailRecord : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *gameTips; // @dynamic gameTips;
@property(nonatomic) unsigned long long receiveAmount; // @dynamic receiveAmount;
@property(retain, nonatomic) NSString *receiveAmountDesc; // @dynamic receiveAmountDesc;
@property(retain, nonatomic) NSString *receiveId; // @dynamic receiveId;
@property(retain, nonatomic) NSString *receiveTime; // @dynamic receiveTime;
@property(nonatomic) unsigned int state; // @dynamic state;
@property(retain, nonatomic) NSString *userName; // @dynamic userName;

@end

