//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GameCenterMsgSender, GameJumpInfo, NSString;

@interface GameCenterMsgV2Node : NSObject
{
    _Bool _dontShowInMsgCenter;
    _Bool _notInMsgCenter;
    unsigned int _mergeCount;
    GameCenterMsgSender *_msgSender;
    GameJumpInfo *_jumpInfo;
    NSString *_primaryContent;
    NSString *_minorContent;
    NSString *_pictureUrl;
    NSString *_sourceName;
    NSString *_mergeId;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool notInMsgCenter; // @synthesize notInMsgCenter=_notInMsgCenter;
@property(nonatomic) unsigned int mergeCount; // @synthesize mergeCount=_mergeCount;
@property(retain, nonatomic) NSString *mergeId; // @synthesize mergeId=_mergeId;
@property(retain, nonatomic) NSString *sourceName; // @synthesize sourceName=_sourceName;
@property(retain, nonatomic) NSString *pictureUrl; // @synthesize pictureUrl=_pictureUrl;
@property(retain, nonatomic) NSString *minorContent; // @synthesize minorContent=_minorContent;
@property(retain, nonatomic) NSString *primaryContent; // @synthesize primaryContent=_primaryContent;
@property(retain, nonatomic) GameJumpInfo *jumpInfo; // @synthesize jumpInfo=_jumpInfo;
@property(retain, nonatomic) GameCenterMsgSender *msgSender; // @synthesize msgSender=_msgSender;
@property(nonatomic) _Bool dontShowInMsgCenter; // @synthesize dontShowInMsgCenter=_dontShowInMsgCenter;

@end

