//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GCDynamicLayoutProvider.h"

@class UIFont;

@interface GCChatBaseCellModelCommonLayout : GCDynamicLayoutProvider
{
    double _headImgTopOffset;
    double _nameLineHeight;
    double _nameLabelFontSize;
    UIFont *_nameLabelFont;
    double _textFontSize;
    double _textLineHeight;
    double _roleLabelFontSize;
    double _noticeLabelFontSize;
    double _headImgWidth;
    double _statusBgWidth;
    double _statusImgWidth;
    double _sendFailViewWidth;
    struct UIEdgeInsets _contentMarginInsets;
    struct UIEdgeInsets _emoticonMarginInsets;
}

- (void).cxx_destruct;
@property(nonatomic) double sendFailViewWidth; // @synthesize sendFailViewWidth=_sendFailViewWidth;
@property(nonatomic) double statusImgWidth; // @synthesize statusImgWidth=_statusImgWidth;
@property(nonatomic) double statusBgWidth; // @synthesize statusBgWidth=_statusBgWidth;
@property(nonatomic) double headImgWidth; // @synthesize headImgWidth=_headImgWidth;
@property(nonatomic) double noticeLabelFontSize; // @synthesize noticeLabelFontSize=_noticeLabelFontSize;
@property(nonatomic) double roleLabelFontSize; // @synthesize roleLabelFontSize=_roleLabelFontSize;
@property(nonatomic) double textLineHeight; // @synthesize textLineHeight=_textLineHeight;
@property(nonatomic) double textFontSize; // @synthesize textFontSize=_textFontSize;
@property(retain, nonatomic) UIFont *nameLabelFont; // @synthesize nameLabelFont=_nameLabelFont;
@property(nonatomic) double nameLabelFontSize; // @synthesize nameLabelFontSize=_nameLabelFontSize;
@property(nonatomic) double nameLineHeight; // @synthesize nameLineHeight=_nameLineHeight;
@property(nonatomic) double headImgTopOffset; // @synthesize headImgTopOffset=_headImgTopOffset;
@property(nonatomic) struct UIEdgeInsets emoticonMarginInsets; // @synthesize emoticonMarginInsets=_emoticonMarginInsets;
@property(nonatomic) struct UIEdgeInsets contentMarginInsets; // @synthesize contentMarginInsets=_contentMarginInsets;
- (id)init;

@end

