//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GCReportBaseVc.h"

#import "GCBaseGroupCellModelDelegate-Protocol.h"
#import "GCChatRoomImageZoomAnimationDelegate-Protocol.h"
#import "GCLoadMoreProtocol-Protocol.h"

@class GCCollectionViewManager, GCCollectionViewSectionModel, GCGroupServer, GCLoadingMoreCellModel, NSString, UICollectionView;

@interface GCMoreCommendGroupViewController : GCReportBaseVc <GCLoadMoreProtocol, GCBaseGroupCellModelDelegate, GCChatRoomImageZoomAnimationDelegate>
{
    GCCollectionViewManager *_collectionViewManager;
    UICollectionView *_collectionView;
    GCGroupServer *_groupServer;
    GCCollectionViewSectionModel *_sectionModel;
    GCLoadingMoreCellModel *_loadMoreCellModel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GCLoadingMoreCellModel *loadMoreCellModel; // @synthesize loadMoreCellModel=_loadMoreCellModel;
@property(retain, nonatomic) GCCollectionViewSectionModel *sectionModel; // @synthesize sectionModel=_sectionModel;
@property(retain, nonatomic) GCGroupServer *groupServer; // @synthesize groupServer=_groupServer;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) GCCollectionViewManager *collectionViewManager; // @synthesize collectionViewManager=_collectionViewManager;
- (struct CGRect)collectionViewFrame;
- (void)onMoreChatRoomRespone:(id)arg1;
- (struct CGRect)getImgFrameWithIdentifier:(id)arg1;
- (void)onOpenChatRoomConfig:(id)arg1 cellModel:(id)arg2;
- (void)onLoadMoreData;
- (void)viewDidLayoutSubviews;
- (void)loadMoreChatRoom;
- (void)viewDidLoad;
- (id)navigationBarBackgroundColor;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

