//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GCTextCellLayoutInfo, NSString;

@interface GCTextCellModelEasyConfig : NSObject
{
    _Bool _showHead;
    NSString *_text;
    GCTextCellLayoutInfo *_layoutInfo;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool showHead; // @synthesize showHead=_showHead;
@property(retain, nonatomic) GCTextCellLayoutInfo *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;

@end

