//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseResponse, NSMutableArray, NSString;

@interface GetWecoinPriceListResponse : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) int agreementStatus; // @dynamic agreementStatus;
@property(retain, nonatomic) NSString *agreementUrl; // @dynamic agreementUrl;
@property(nonatomic) unsigned int agreementVersion; // @dynamic agreementVersion;
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) NSMutableArray *priceInfos; // @dynamic priceInfos;

@end

