//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray;

@protocol GoodsPubbleUpdateExt <NSObject>

@optional
- (void)onEndIssueCouponForGoodsPubbleDisplay:(NSArray *)arg1;
- (void)onNewIssueCouponForGoodsPubbleDisplay:(NSArray *)arg1;
- (void)onEndAdPromoteForGoodsPubbleDisplay:(NSArray *)arg1;
- (void)onNewAdPromoteForGoodsPubbleDisplay:(NSArray *)arg1;
- (void)onEndProductPromoteForGoodsPubbleDisplay:(NSArray *)arg1;
- (void)onNewProductPromoteForGoodsPubbleDisplay:(NSArray *)arg1;
@end

