//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "OpenUploadCDNMgrDelegate-Protocol.h"
#import "RecordUploadCDNMgrDelegate-Protocol.h"
#import "UploadImageCDNMgrDelegate-Protocol.h"
#import "UploadVideoCDNMgrDelegate-Protocol.h"

@class CMessageWrap, NSString, OpenUploadCDNMgr, OpenUploadVideoCDNMgr, RecordUploadCDNMgr, UploadImageCDNMgr, UploadVideoCDNMgr;
@protocol HistoryMsgUploadTaskDelegate;

@interface HistoryMsgUploadTask : NSObject <UploadImageCDNMgrDelegate, UploadVideoCDNMgrDelegate, RecordUploadCDNMgrDelegate, OpenUploadCDNMgrDelegate>
{
    CMessageWrap *_msgWrap;
    id <HistoryMsgUploadTaskDelegate> _delegate;
    UploadImageCDNMgr *_uploadImageCdnMgr;
    UploadVideoCDNMgr *_uploadVideoCdnMgr;
    RecordUploadCDNMgr *_recordUploadCDNMgr;
    OpenUploadCDNMgr *_openUploadCDNMgr;
    OpenUploadVideoCDNMgr *_openUploadVideoCDNMgr;
}

- (void).cxx_destruct;
@property(retain, nonatomic) OpenUploadVideoCDNMgr *openUploadVideoCDNMgr; // @synthesize openUploadVideoCDNMgr=_openUploadVideoCDNMgr;
@property(retain, nonatomic) OpenUploadCDNMgr *openUploadCDNMgr; // @synthesize openUploadCDNMgr=_openUploadCDNMgr;
@property(retain, nonatomic) RecordUploadCDNMgr *recordUploadCDNMgr; // @synthesize recordUploadCDNMgr=_recordUploadCDNMgr;
@property(retain, nonatomic) UploadVideoCDNMgr *uploadVideoCdnMgr; // @synthesize uploadVideoCdnMgr=_uploadVideoCdnMgr;
@property(retain, nonatomic) UploadImageCDNMgr *uploadImageCdnMgr; // @synthesize uploadImageCdnMgr=_uploadImageCdnMgr;
@property(nonatomic) __weak id <HistoryMsgUploadTaskDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) CMessageWrap *msgWrap; // @synthesize msgWrap=_msgWrap;
- (void)OnUploadMsgDataFail:(id)arg1;
- (void)OnUploadRecordMsgDataSuccess:(id)arg1;
- (void)OnUploadMsgDataSuccess:(id)arg1 hitMD5:(_Bool)arg2;
- (void)stopUpload;
- (void)startUpload;
- (id)genImageMsgWrap:(id)arg1;
- (id)genOpenUploadQueuePath;
- (id)initWithDelegate:(id)arg1 MsgWrap:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

