//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IWAAuthorizeAddAvatarViewControllerParams : NSObject
{
    unsigned int _sessionId;
    NSString *_appId;
    NSString *_defaultAvatarUrl;
    NSString *_defaultAvatarFileId;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int sessionId; // @synthesize sessionId=_sessionId;
@property(copy, nonatomic) NSString *defaultAvatarFileId; // @synthesize defaultAvatarFileId=_defaultAvatarFileId;
@property(copy, nonatomic) NSString *defaultAvatarUrl; // @synthesize defaultAvatarUrl=_defaultAvatarUrl;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;

@end

