//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "LocalJSEventHandlerContextDelegate-Protocol.h"

@class NSMutableArray, NSMutableSet, NSString, WKWebView;
@protocol WSWebViewPluginableProtocol, YYWebViewInterface;

@interface LocalJSLogicBase : MMObject <LocalJSEventHandlerContextDelegate>
{
    WKWebView<YYWebViewInterface> *_webView;
    NSMutableArray *_authApiList;
    _Bool _bridgeCompleted;
    id <WSWebViewPluginableProtocol> _webViewOwner;
    NSMutableSet *_jsEvents;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool bridgeCompleted; // @synthesize bridgeCompleted=_bridgeCompleted;
@property(retain, nonatomic) NSMutableSet *jsEvents; // @synthesize jsEvents=_jsEvents;
@property(nonatomic) __weak id <WSWebViewPluginableProtocol> webViewOwner; // @synthesize webViewOwner=_webViewOwner;
- (id)getWebViewOwner;
- (unsigned long long)getLocalJSBusinessType;
- (void)sendEvent:(id)arg1 handler:(id)arg2 result:(id)arg3;
- (void)eventEndWithHandler:(id)arg1 result:(id)arg2;
- (id)webview;
- (void)removeAllJSEvent;
- (_Bool)canUseClassHandleJSAPI:(id)arg1;
- (void)ackWithCallBackID:(id)arg1 errorMsg:(id)arg2;
- (void)ackWithCallBackID:(id)arg1 withParams:(id)arg2;
- (id)getNetworkInfo;
- (_Bool)isOnDawangEnv;
- (void)handleJSApiFuncOfGetNetworkType:(id)arg1 withCallBackID:(id)arg2;
- (void)functionCall:(id)arg1 withParams:(id)arg2 withCallbackID:(id)arg3;
- (void)reSetWebView:(id)arg1;
- (void)addAuthApiList:(id)arg1;
- (void)sendJSCBEventToJSBridge:(id)arg1 withCallBackID:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)sendJSCBEventToJSBridge:(id)arg1 withCallBackID:(id)arg2;
- (void)dispatchEventHandler:(id)arg1 withParams:(id)arg2;
- (void)dispatchEventHandler:(id)arg1 withParams:(id)arg2 withCallbackID:(id)arg3;
- (void)handleJSApiDispatchMessage:(id)arg1;
- (void)sendEventToJSBridge:(id)arg1 params:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)sendEventToJSBridge:(id)arg1 params:(id)arg2;
- (void)onJsEvaluateError:(id)arg1;
- (void)sendMessageToJSBridge:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)injectWeixinJSBridge;
- (void)onSysBridgeCompleted;
- (void)tryInjectWeixinJSBridge:(id)arg1;
- (id)initWithWebView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

