//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAVVLogEffect.h"

#import "MAVTextureInfoEffect-Protocol.h"

@class MAVPixelHelper;

@interface MAVBlendEffect : MAVVLogEffect <MAVTextureInfoEffect>
{
    struct __CVOpenGLESTextureCache *_textureCache;
    MAVPixelHelper *_pixelHelper;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MAVPixelHelper *pixelHelper; // @synthesize pixelHelper=_pixelHelper;
@property(nonatomic) struct __CVOpenGLESTextureCache *textureCache; // @synthesize textureCache=_textureCache;
- (void)dealloc;
- (void)setTextureInfoWithPixelBuf:(struct __CVBuffer *)arg1;
- (void)setTextureInfo:(int)arg1 width:(int)arg2 height:(int)arg3;
- (void)setIsPreMultiplied:(_Bool)arg1;
- (long long)type;
- (id)initWithPtr:(shared_ptr_588f9d5a)arg1;

@end

