//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MBJSContext.h"

@class MBJITHandler;

@interface MBJITJSContext : MBJSContext
{
    MBJITHandler *_handler;
}

- (void).cxx_destruct;
@property(nonatomic) __weak MBJITHandler *handler; // @synthesize handler=_handler;
- (void)evaluateScript:(id)arg1 sourceURL:(id)arg2;

@end

