//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"
#import "WCTTableCoding-Protocol.h"

@class MinimizeTaskContainerInfo, MinimizeTaskExtInfo, NSArray, NSData, NSString;

@interface MinimizeTaskData : MMObject <PBCoding, WCTTableCoding>
{
    _Bool isForeground;
    _Bool shouldIgnoreSubtitleWhenRecoverTask;
    _Bool _bForbidAddDuplicateTask;
    _Bool _isNew;
    _Bool _canMaximizeForStateView;
    unsigned int _taskCreateTime;
    int _currentTransitionType;
    unsigned int _taskStateType;
    NSString *taskBizName;
    NSString *taskBizKey;
    NSData *taskContextData;
    NSString *taskDefaultIconName;
    NSData *taskIconImgData;
    NSString *taskIconUrl;
    NSString *taskTitle;
    NSString *taskSubtitle;
    NSString *taskKey;
    NSString *delegateClassName;
    NSString *taskTitleTail;
    MinimizeTaskExtInfo *taskExtInfo;
    NSString *_taskDisplaySourceName;
    NSString *_taskFooterText;
    NSString *_taskDefaultThumbImgName;
    NSData *_taskThumbImgData;
    NSString *_taskThumbUrl;
    NSString *_taskSubtitleTail;
    unsigned long long _directLaunchType;
    NSArray *_taskStateList;
    MinimizeTaskContainerInfo *_containerInfo;
    unsigned long long _sizeChangedAnimAnchorPoint;
}

+ (CDUnknownBlockType)comparator;
+ (void)initialize;
+ (void)PBArrayAdd_shouldIgnoreSubtitleWhenRecoverTask;
+ (void)PBArrayAdd_taskExtInfo;
+ (void)PBArrayAdd_taskTitleTail;
+ (void)PBArrayAdd_delegateClassName;
+ (void)PBArrayAdd_taskKey;
+ (void)PBArrayAdd_isForeground;
+ (void)PBArrayAdd_taskSubtitle;
+ (void)PBArrayAdd_taskTitle;
+ (void)PBArrayAdd_taskIconUrl;
+ (void)PBArrayAdd_taskIconImgData;
+ (void)PBArrayAdd_taskDefaultIconName;
+ (void)PBArrayAdd_taskContextData;
+ (void)PBArrayAdd_taskBizKey;
+ (void)PBArrayAdd_taskBizName;
+ (void)__wcdb_index_19:(struct WCTBinding *)arg1;
+ (void)__wcdb_index_18:(struct WCTBinding *)arg1;
+ (void)__wcdb_column_constraint_17:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_16:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskFooterText;
+ (const struct WCTProperty *)__wcdb_synthesize_15:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskTitleTail;
+ (const struct WCTProperty *)__wcdb_synthesize_14:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskSubtitle;
+ (const struct WCTProperty *)__wcdb_synthesize_13:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskTitle;
+ (const struct WCTProperty *)__wcdb_synthesize_12:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskDisplaySourceName;
+ (const struct WCTProperty *)__wcdb_synthesize_11:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskIconUrl;
+ (const struct WCTProperty *)__wcdb_synthesize_10:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskIconImgData;
+ (const struct WCTProperty *)__wcdb_synthesize_9:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskDefaultIconName;
+ (const struct WCTProperty *)__wcdb_synthesize_8:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskThumbUrl;
+ (const struct WCTProperty *)__wcdb_synthesize_7:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskThumbImgData;
+ (const struct WCTProperty *)__wcdb_synthesize_6:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskDefaultThumbImgName;
+ (const struct WCTProperty *)__wcdb_synthesize_5:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)delegateClassName;
+ (const struct WCTProperty *)__wcdb_synthesize_4:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskKey;
+ (const struct WCTProperty *)__wcdb_synthesize_3:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskCreateTime;
+ (const struct WCTProperty *)__wcdb_synthesize_2:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskContextData;
+ (const struct WCTProperty *)__wcdb_synthesize_1:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskBizKey;
+ (const struct WCTProperty *)__wcdb_synthesize_0:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)taskBizName;
+ (id)__wcdbtyper;
+ (const SyntaxList_7f15fe8c *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long sizeChangedAnimAnchorPoint; // @synthesize sizeChangedAnimAnchorPoint=_sizeChangedAnimAnchorPoint;
@property(nonatomic) _Bool canMaximizeForStateView; // @synthesize canMaximizeForStateView=_canMaximizeForStateView;
@property(retain, nonatomic) MinimizeTaskContainerInfo *containerInfo; // @synthesize containerInfo=_containerInfo;
@property(nonatomic) unsigned int taskStateType; // @synthesize taskStateType=_taskStateType;
@property(retain, nonatomic) NSArray *taskStateList; // @synthesize taskStateList=_taskStateList;
@property(nonatomic) int currentTransitionType; // @synthesize currentTransitionType=_currentTransitionType;
@property(nonatomic) _Bool isNew; // @synthesize isNew=_isNew;
@property(nonatomic) unsigned long long directLaunchType; // @synthesize directLaunchType=_directLaunchType;
@property(nonatomic) _Bool bForbidAddDuplicateTask; // @synthesize bForbidAddDuplicateTask=_bForbidAddDuplicateTask;
@property(retain, nonatomic) NSString *taskSubtitleTail; // @synthesize taskSubtitleTail=_taskSubtitleTail;
@property(retain, nonatomic) NSString *taskThumbUrl; // @synthesize taskThumbUrl=_taskThumbUrl;
@property(retain, nonatomic) NSData *taskThumbImgData; // @synthesize taskThumbImgData=_taskThumbImgData;
@property(retain, nonatomic) NSString *taskDefaultThumbImgName; // @synthesize taskDefaultThumbImgName=_taskDefaultThumbImgName;
@property(retain, nonatomic) NSString *taskFooterText; // @synthesize taskFooterText=_taskFooterText;
@property(retain, nonatomic) NSString *taskDisplaySourceName; // @synthesize taskDisplaySourceName=_taskDisplaySourceName;
@property(nonatomic) unsigned int taskCreateTime; // @synthesize taskCreateTime=_taskCreateTime;
@property(nonatomic) _Bool shouldIgnoreSubtitleWhenRecoverTask; // @synthesize shouldIgnoreSubtitleWhenRecoverTask;
@property(retain, nonatomic) MinimizeTaskExtInfo *taskExtInfo; // @synthesize taskExtInfo;
@property(retain, nonatomic) NSString *taskTitleTail; // @synthesize taskTitleTail;
@property(retain, nonatomic) NSString *delegateClassName; // @synthesize delegateClassName;
@property(retain, nonatomic) NSString *taskKey; // @synthesize taskKey;
@property(nonatomic) _Bool isForeground; // @synthesize isForeground;
@property(retain, nonatomic) NSString *taskSubtitle; // @synthesize taskSubtitle;
@property(retain, nonatomic) NSString *taskTitle; // @synthesize taskTitle;
@property(retain, nonatomic) NSString *taskIconUrl; // @synthesize taskIconUrl;
@property(retain, nonatomic) NSData *taskIconImgData; // @synthesize taskIconImgData;
@property(retain, nonatomic) NSString *taskDefaultIconName; // @synthesize taskDefaultIconName;
@property(retain, nonatomic) NSData *taskContextData; // @synthesize taskContextData;
@property(retain, nonatomic) NSString *taskBizKey; // @synthesize taskBizKey;
@property(retain, nonatomic) NSString *taskBizName; // @synthesize taskBizName;
@property(readonly, copy) NSString *description;
- (_Bool)isStateEqualTo:(id)arg1;
- (_Bool)isTaskIconEqualTo:(id)arg1;
- (void)copyInternalInfoFrom:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;
@property(readonly) Class superclass;

@end

