//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

#import "GetQRCodeInfoLogicDelegate-Protocol.h"

@class GetQRCodeInfoLogic, MMScrollableActionSheetVerticalRowInfo, MMWebImageView, NSString, UIButton, UIImageView, UILabel;
@protocol MMActionSheetQRCodeRowViewDelegate;

@interface MMActionSheetQRCodeRowView : MMUIView <GetQRCodeInfoLogicDelegate>
{
    _Bool _isUrlInfoHasUpdated;
    unsigned int _businessType;
    MMScrollableActionSheetVerticalRowInfo *_rowInfo;
    id <MMActionSheetQRCodeRowViewDelegate> _delegate;
    UIButton *_backgroundButton;
    UIImageView *_loadingView;
    MMWebImageView *_iconImageView;
    UIImageView *_arrowImageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    GetQRCodeInfoLogic *_qrCodeInfoLogic;
    NSString *_codeStr;
    NSString *_title;
}

+ (double)rowViewHeight;
- (void).cxx_destruct;
@property(nonatomic) unsigned int businessType; // @synthesize businessType=_businessType;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *codeStr; // @synthesize codeStr=_codeStr;
@property(nonatomic) _Bool isUrlInfoHasUpdated; // @synthesize isUrlInfoHasUpdated=_isUrlInfoHasUpdated;
@property(retain, nonatomic) GetQRCodeInfoLogic *qrCodeInfoLogic; // @synthesize qrCodeInfoLogic=_qrCodeInfoLogic;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) MMWebImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIImageView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIButton *backgroundButton; // @synthesize backgroundButton=_backgroundButton;
@property(nonatomic) __weak id <MMActionSheetQRCodeRowViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MMScrollableActionSheetVerticalRowInfo *rowInfo; // @synthesize rowInfo=_rowInfo;
- (void)onGetQRCodeInfoResultSuccess:(unsigned int)arg1 qrCodeInfoItem:(id)arg2;
- (void)onGetQRCodeInfoResultFailure:(unsigned int)arg1;
- (void)updateRowInfoUseDefaultInfo:(unsigned int)arg1;
- (void)onTimeout:(id)arg1;
- (void)cancelQRCodeInfoCallback;
- (void)getQRCodeInfo;
- (void)onTappedRowInfo;
- (void)layoutSubviews;
- (void)setupAllSubviews;
- (void)updateQRCodeInfo;
- (id)initWithCodeType:(unsigned int)arg1 codeStr:(id)arg2 title:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

