//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMAppSceneUtil : NSObject
{
}

+ (_Bool)isMainScene:(id)arg1;
+ (id)lastActiveSceneRootWindow;
+ (id)lastActiveWindowScene;
+ (id)subWindowScene;
+ (id)mainWindowScene;
+ (_Bool)isShowInSubScene:(id)arg1;
+ (_Bool)isMainSceneActive;
+ (_Bool)isSubSceneActive;
+ (_Bool)isMultiSceneSupported;

@end

