//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, UITableView, UIView;

@interface MMDragDownAnimateHelper : NSObject
{
    _Bool _disableDragDown;
    _Bool _isAtDragDownState;
    _Bool _hasTriggerDragShock;
    double _hoverTargetOffset;
    double _expandedHeight;
    UITableView *_frontTableView;
    UIView *_frontContainerView;
    double _frontViewTop;
    NSDate *_dragStartTime;
    double _lastMovement;
    double _beginTouchPosY;
    double _lastTouchPosY;
    double _frontViewY;
    double _currentDragProgress;
    CDUnknownBlockType _enterHoverAnimation;
    CDUnknownBlockType _enterHoverCompletion;
    CDUnknownBlockType _exitHoverAnimation;
    CDUnknownBlockType _exitHoverCompletion;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType exitHoverCompletion; // @synthesize exitHoverCompletion=_exitHoverCompletion;
@property(copy, nonatomic) CDUnknownBlockType exitHoverAnimation; // @synthesize exitHoverAnimation=_exitHoverAnimation;
@property(copy, nonatomic) CDUnknownBlockType enterHoverCompletion; // @synthesize enterHoverCompletion=_enterHoverCompletion;
@property(copy, nonatomic) CDUnknownBlockType enterHoverAnimation; // @synthesize enterHoverAnimation=_enterHoverAnimation;
@property(nonatomic) double currentDragProgress; // @synthesize currentDragProgress=_currentDragProgress;
@property(nonatomic) _Bool hasTriggerDragShock; // @synthesize hasTriggerDragShock=_hasTriggerDragShock;
@property(nonatomic) double frontViewY; // @synthesize frontViewY=_frontViewY;
@property(nonatomic) double lastTouchPosY; // @synthesize lastTouchPosY=_lastTouchPosY;
@property(nonatomic) double beginTouchPosY; // @synthesize beginTouchPosY=_beginTouchPosY;
@property(nonatomic) double lastMovement; // @synthesize lastMovement=_lastMovement;
@property(retain, nonatomic) NSDate *dragStartTime; // @synthesize dragStartTime=_dragStartTime;
@property(nonatomic) double frontViewTop; // @synthesize frontViewTop=_frontViewTop;
@property(nonatomic) __weak UIView *frontContainerView; // @synthesize frontContainerView=_frontContainerView;
@property(nonatomic) __weak UITableView *frontTableView; // @synthesize frontTableView=_frontTableView;
@property(nonatomic) double expandedHeight; // @synthesize expandedHeight=_expandedHeight;
@property(nonatomic) _Bool isAtDragDownState; // @synthesize isAtDragDownState=_isAtDragDownState;
@property(nonatomic) double hoverTargetOffset; // @synthesize hoverTargetOffset=_hoverTargetOffset;
@property(nonatomic) _Bool disableDragDown; // @synthesize disableDragDown=_disableDragDown;
- (void)lightShock;
- (void)exitDragDownState:(_Bool)arg1;
- (void)enterDragDownState:(_Bool)arg1;
- (_Bool)canTrigerAtPositionY:(double)arg1;
- (double)progressForCurrentOffset:(double)arg1;
- (void)resetFrontViewOffsetAnimated:(_Bool)arg1;
- (void)handleAlphaAnimateWithFrontViewTopOffset:(double)arg1;
- (void)handlePanGestureAtHoverDisable:(id)arg1;
- (void)handlePanGestureAtHoverEnable:(id)arg1;
- (void)processFrontViewGesture:(id)arg1;
- (void)onDidExitDragDownState;
- (void)onWillExitDragDownState;
- (void)onDidEnterDragDownState;
- (void)onWillEnterDragDownState;
- (void)onInitUI;
- (void)onDragDownProgressChange:(double)arg1;
- (void)setExitDragDownAnimation:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setEnterDragDownAnimation:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) double currentDragDownProgress;
- (void)setDisableHover:(_Bool)arg1;
- (void)setupUI;
- (id)initWithFrontContainerView:(id)arg1 frontInitialTop:(double)arg2 frontTableView:(id)arg3;

@end

