//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFinderLiveConnectMicBaseUserInfoView.h"

@class PAGView;

@interface MMFinderLiveConnectMicAudioUserInfoView : MMFinderLiveConnectMicBaseUserInfoView
{
    PAGView *_volumeAnimationView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PAGView *volumeAnimationView; // @synthesize volumeAnimationView=_volumeAnimationView;
- (void)layoutUIAndSizeToFitWithMaxWidth:(double)arg1 looseLayout:(_Bool)arg2;
- (void)updateHeadImageViewWithLooseLayout:(_Bool)arg1;
- (void)configVolumeAnimationView;

@end

