//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMLiveMusicDataItem.h"

@class NSString;

@interface MMFinderLiveMusicDataItem : MMLiveMusicDataItem
{
    _Bool _playable;
    NSString *_musicName;
    NSString *_musicAnchor;
    NSString *_albumName;
    NSString *_albumPicUrl;
    NSString *_genre;
    NSString *_publicTime;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *publicTime; // @synthesize publicTime=_publicTime;
@property(nonatomic) _Bool playable; // @synthesize playable=_playable;
@property(copy, nonatomic) NSString *genre; // @synthesize genre=_genre;
@property(copy, nonatomic) NSString *albumPicUrl; // @synthesize albumPicUrl=_albumPicUrl;
@property(copy, nonatomic) NSString *albumName; // @synthesize albumName=_albumName;
@property(copy, nonatomic) NSString *musicAnchor; // @synthesize musicAnchor=_musicAnchor;
@property(copy, nonatomic) NSString *musicName; // @synthesize musicName=_musicName;
- (id)initWithFinderLiveMusicInfo:(id)arg1;

@end

