//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMFinderLiveConnectMicPKInfo, NSArray, NSData, NSString, WCFinderContact;

@interface MMFinderLiveConnectMicUser : NSObject
{
    _Bool _useVideo;
    _Bool _isConnecting;
    _Bool _isConnectWaiting;
    _Bool _isCloseWaiting;
    _Bool _isSelf;
    _Bool _isAnchor;
    _Bool _hasConnectedOtherRoom;
    _Bool _justApply;
    _Bool _isAudioMode;
    _Bool _isTalking;
    _Bool _remoteMediaDataIsInterrupted;
    _Bool _isRemoteClosed;
    unsigned int _micUserAttrFlag;
    unsigned int _sdkRoomId;
    int _talkingCount;
    unsigned int _audioInterruptedTime;
    WCFinderContact *_connectMicFinderContact;
    NSString *_sdkUserId;
    NSString *_sessionId;
    unsigned long long _sequence;
    unsigned long long _expiredTime;
    NSString *_sdkPkSign;
    NSString *_coverImageUrlString;
    MMFinderLiveConnectMicPKInfo *_pkInfo;
    unsigned long long _randomMicState;
    NSData *_randomMicBuffer;
    NSArray *_badgeInfos;
}

+ (id)connectMicUserFromAnchorContact:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *badgeInfos; // @synthesize badgeInfos=_badgeInfos;
@property(retain, nonatomic) NSData *randomMicBuffer; // @synthesize randomMicBuffer=_randomMicBuffer;
@property(nonatomic) unsigned long long randomMicState; // @synthesize randomMicState=_randomMicState;
@property(nonatomic) unsigned int audioInterruptedTime; // @synthesize audioInterruptedTime=_audioInterruptedTime;
@property(nonatomic) _Bool isRemoteClosed; // @synthesize isRemoteClosed=_isRemoteClosed;
@property(nonatomic) _Bool remoteMediaDataIsInterrupted; // @synthesize remoteMediaDataIsInterrupted=_remoteMediaDataIsInterrupted;
@property(nonatomic) int talkingCount; // @synthesize talkingCount=_talkingCount;
@property(nonatomic) _Bool isTalking; // @synthesize isTalking=_isTalking;
@property(retain, nonatomic) MMFinderLiveConnectMicPKInfo *pkInfo; // @synthesize pkInfo=_pkInfo;
@property(nonatomic) _Bool isAudioMode; // @synthesize isAudioMode=_isAudioMode;
@property(copy, nonatomic) NSString *coverImageUrlString; // @synthesize coverImageUrlString=_coverImageUrlString;
@property(nonatomic) _Bool justApply; // @synthesize justApply=_justApply;
@property(nonatomic) _Bool hasConnectedOtherRoom; // @synthesize hasConnectedOtherRoom=_hasConnectedOtherRoom;
@property(copy, nonatomic) NSString *sdkPkSign; // @synthesize sdkPkSign=_sdkPkSign;
@property(nonatomic) unsigned int sdkRoomId; // @synthesize sdkRoomId=_sdkRoomId;
@property(nonatomic) _Bool isAnchor; // @synthesize isAnchor=_isAnchor;
@property(nonatomic) unsigned int micUserAttrFlag; // @synthesize micUserAttrFlag=_micUserAttrFlag;
@property(nonatomic) unsigned long long expiredTime; // @synthesize expiredTime=_expiredTime;
@property(nonatomic) _Bool isSelf; // @synthesize isSelf=_isSelf;
@property(nonatomic) unsigned long long sequence; // @synthesize sequence=_sequence;
@property(copy, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(copy, nonatomic) NSString *sdkUserId; // @synthesize sdkUserId=_sdkUserId;
@property(nonatomic) _Bool isCloseWaiting; // @synthesize isCloseWaiting=_isCloseWaiting;
@property(nonatomic) _Bool isConnectWaiting; // @synthesize isConnectWaiting=_isConnectWaiting;
@property(nonatomic) _Bool isConnecting; // @synthesize isConnecting=_isConnecting;
@property(nonatomic) _Bool useVideo; // @synthesize useVideo=_useVideo;
@property(retain, nonatomic) WCFinderContact *connectMicFinderContact; // @synthesize connectMicFinderContact=_connectMicFinderContact;
- (void)updateBadgeInfo:(id)arg1;
@property(readonly, nonatomic) _Bool isFinderAuthor;
@property(readonly, nonatomic) _Bool needInvite;
- (void)resetPkInfo;
- (_Bool)isSelfUser;
- (id)init;

@end

