//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMMultiMenuTableViewCell.h"

@class MMFinderLiveCouponView;
@protocol MMFinderLiveCouponViewDelegate;

@interface MMFinderLiveCouponCell : MMMultiMenuTableViewCell
{
    _Bool _isAnchor;
    id <MMFinderLiveCouponViewDelegate> _delegate;
    MMFinderLiveCouponView *_couponView;
}

+ (double)getCellHeight:(_Bool)arg1;
+ (id)identifier;
- (void).cxx_destruct;
@property(nonatomic) _Bool isAnchor; // @synthesize isAnchor=_isAnchor;
@property(retain, nonatomic) MMFinderLiveCouponView *couponView; // @synthesize couponView=_couponView;
@property(nonatomic) __weak id <MMFinderLiveCouponViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)fillWithViewModel:(id)arg1;
- (void)layoutUI;
- (void)removeExtraSeperateLine;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 isAnchor:(_Bool)arg3;

@end

