//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class LOTAnimationView, MMTimerLabel, NSString;

@interface MMFinderLiveLittleLotteryPacketView : UIView
{
    unsigned int _remainTime;
    unsigned int _currentLotteryStatus;
    CDUnknownBlockType _countDownCompleteCallback;
    CDUnknownBlockType _countDownRemainTimeCallback;
    long long _currentState;
    LOTAnimationView *_pagPacketView;
    MMTimerLabel *_tipLabel;
    NSString *_tipContent;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *tipContent; // @synthesize tipContent=_tipContent;
@property(retain, nonatomic) MMTimerLabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) LOTAnimationView *pagPacketView; // @synthesize pagPacketView=_pagPacketView;
@property(nonatomic) unsigned int currentLotteryStatus; // @synthesize currentLotteryStatus=_currentLotteryStatus;
@property(nonatomic) long long currentState; // @synthesize currentState=_currentState;
@property(copy, nonatomic) CDUnknownBlockType countDownRemainTimeCallback; // @synthesize countDownRemainTimeCallback=_countDownRemainTimeCallback;
@property(copy, nonatomic) CDUnknownBlockType countDownCompleteCallback; // @synthesize countDownCompleteCallback=_countDownCompleteCallback;
@property(nonatomic) unsigned int remainTime; // @synthesize remainTime=_remainTime;
- (unsigned int)currentRemainTime;
- (void)stopDisplay;
- (void)stopCountDown;
- (void)startCountDown;
- (void)convertRemainTimeToHour:(unsigned int *)arg1 minute:(unsigned int *)arg2 second:(unsigned int *)arg3;
- (void)startDisplayAnimated;
- (void)layoutTipLabel;
- (void)layoutPagPacketView;
- (void)layoutUI;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

