//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FinderLiveGift;

@interface MMFinderLiveRecentRewardGiftItem : NSObject
{
    unsigned int _productCount;
    FinderLiveGift *_gift;
}

+ (id)batchConvert:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned int productCount; // @synthesize productCount=_productCount;
@property(retain, nonatomic) FinderLiveGift *gift; // @synthesize gift=_gift;
@property(readonly, nonatomic) double lengthAtLast;
@property(readonly, nonatomic) double length;
- (id)initWithFinderLiveGift:(id)arg1 count:(unsigned int)arg2;

@end

