//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMFinderLiveNotifyStyleCommentPubbleCell.h"

@class MMFinderLiveGlobalRankSignView, MMUILabel, MMUIView, UIView;

@interface MMFinderLiveNotifyStyleTopCommentPubbleCell : MMFinderLiveNotifyStyleCommentPubbleCell
{
    UIView *_lineView;
    MMUILabel *_signLabel;
    MMUIView *_signBackView;
    MMFinderLiveGlobalRankSignView *_globalRankSignView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMFinderLiveGlobalRankSignView *globalRankSignView; // @synthesize globalRankSignView=_globalRankSignView;
@property(retain, nonatomic) MMUIView *signBackView; // @synthesize signBackView=_signBackView;
@property(retain, nonatomic) MMUILabel *signLabel; // @synthesize signLabel=_signLabel;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
- (_Bool)needDisplayGlobalRank;
- (void)updateGlobalSignLabelOrigin;
- (void)layoutGlobalRankSignView;
- (_Bool)needSignLabel;
- (id)signText;
- (void)updateSignLabelOrigin;
- (void)layoutSignLabel;
- (void)updateLineView;
- (void)layoutLineView;
- (void)updateNickLabelOrigin;
- (void)layoutNickLabel;
- (void)updateCommentLabelOrigin;
- (double)getFirstLineBottom;
- (void)layoutCommentLabel;
- (void)layoutSubviews;
- (id)initWithCellFrame:(id)arg1;

@end

