//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMLiveCommentTableViewCellFrame.h"

@class MMLiveCommentPubbleCellFrame, NSString;

@interface MMFinderLiveCommentTableViewCellFrame : MMLiveCommentTableViewCellFrame
{
    long long _layoutResult;
    MMLiveCommentPubbleCellFrame *_pubbleCellFrame;
    double _currentCellHeight;
    double _cellHeightPortrait;
    double _cellHeightLandscape;
    double _layoutStandardWidth;
    NSString *_layoutIdentityKey;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *layoutIdentityKey; // @synthesize layoutIdentityKey=_layoutIdentityKey;
@property(nonatomic) double layoutStandardWidth; // @synthesize layoutStandardWidth=_layoutStandardWidth;
@property(nonatomic) double cellHeightLandscape; // @synthesize cellHeightLandscape=_cellHeightLandscape;
@property(nonatomic) double cellHeightPortrait; // @synthesize cellHeightPortrait=_cellHeightPortrait;
@property(nonatomic) double currentCellHeight; // @synthesize currentCellHeight=_currentCellHeight;
@property(retain, nonatomic) MMLiveCommentPubbleCellFrame *pubbleCellFrame; // @synthesize pubbleCellFrame=_pubbleCellFrame;
- (_Bool)isCurrentLayouted;
- (void)lazyCommentLayoutCurrent;
- (double)currCellHeight;
- (double)cellHeight;
- (void)resetCellFrame;
- (void)calculateWithCommentInfo:(id)arg1 isLastLine:(_Bool)arg2;

@end

