//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "MMLiveTaskMgrExt-Protocol.h"
#import "MMServiceProtocol-Protocol.h"

@class MMLiveLikePostTask, NSMutableArray, NSString, SafeMutableDictionary;

@interface MMLiveLikeDataMgr : MMUserService <MMServiceProtocol, MMLiveTaskMgrExt>
{
    _Bool _isPosting;
    SafeMutableDictionary *_likeInfoDict;
    NSMutableArray *_postTaskQueue;
    MMLiveLikePostTask *_postingTask;
}

+ (id)getLikeCountLabel:(unsigned long long)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) MMLiveLikePostTask *postingTask; // @synthesize postingTask=_postingTask;
@property(retain, nonatomic) NSMutableArray *postTaskQueue; // @synthesize postTaskQueue=_postTaskQueue;
@property(nonatomic) _Bool isPosting; // @synthesize isPosting=_isPosting;
@property(retain, nonatomic) SafeMutableDictionary *likeInfoDict; // @synthesize likeInfoDict=_likeInfoDict;
- (void)handleApplyLikeResult:(id)arg1 forTaskId:(id)arg2;
- (_Bool)applyLikeWithPostTask:(id)arg1;
- (void)onExitLiveSuccessWithLiveTask:(id)arg1;
- (id)getLikeInfoWithoutCreatedWithTaskId:(id)arg1;
- (id)getLikeInfoWithTaskId:(id)arg1;
- (id)getMergedPostTask;
- (void)postNextTask;
- (void)updateLikeCountWithoutCreate:(unsigned long long)arg1 forTaskId:(id)arg2;
- (void)setLikeCount:(unsigned long long)arg1 forTaskId:(id)arg2;
- (id)getOtherLikeContactListForAudience:(id)arg1 withTaskId:(id)arg2;
- (unsigned long long)getLikeCountForAchorWithTaskId:(id)arg1;
- (unsigned long long)getOthersLikeCountForAudienceWithTaskId:(id)arg1;
- (unsigned long long)getLikeCountForAudienceWithTaskId:(id)arg1;
- (void)postLiveLikeWithTaskId:(id)arg1 isClipMode:(_Bool)arg2;
- (void)unRegisterExtension;
- (void)registerExtension;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

