//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray;

@protocol MMLiveCommentViewDelegate <NSObject>

@optional
- (void)onVerifyRealNameForComment;
- (NSArray *)getLiveCommentViewCustomHitViews;
- (_Bool)getIsShoppingAvailable;
- (double)getCommentButtonLeft;
- (double)getCommentTableTop;
- (double)getCommentTableLandscapeBottom;
- (double)getCommentTableBottom;
- (double)getBottomWidgetsBottom;
- (double)getRightWidgetsLeft;
- (double)getTopWidgetsBottom;
- (void)onBackViewDidTaped;
- (void)updateButtonHiddenForInputViewShowChange:(_Bool)arg1;
- (double)getVisibleHeight;
@end

