//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMLiveTaskId, MMUIButton, UILabel;
@protocol MMLiveCameraOperationPanelDelegate;

@interface MMLiveCameraOperationPanel : UIView
{
    id <MMLiveCameraOperationPanelDelegate> _actionDelegate;
    MMLiveTaskId *_taskId;
    UIView *_panelView;
    MMUIButton *_backgroundExitButton;
    MMUIButton *_switchCameraButton;
    UILabel *_switchCameraTipLabel;
    MMUIButton *_mirrorButton;
    UILabel *_mirrorTipLabel;
    MMUIButton *_filterButton;
    UILabel *_filterTipLabel;
    MMUIButton *_beautyButton;
    UILabel *_beautyTipLabel;
    MMUIButton *_cameraButton;
    UILabel *_cameraTipLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *cameraTipLabel; // @synthesize cameraTipLabel=_cameraTipLabel;
@property(retain, nonatomic) MMUIButton *cameraButton; // @synthesize cameraButton=_cameraButton;
@property(retain, nonatomic) UILabel *beautyTipLabel; // @synthesize beautyTipLabel=_beautyTipLabel;
@property(retain, nonatomic) MMUIButton *beautyButton; // @synthesize beautyButton=_beautyButton;
@property(retain, nonatomic) UILabel *filterTipLabel; // @synthesize filterTipLabel=_filterTipLabel;
@property(retain, nonatomic) MMUIButton *filterButton; // @synthesize filterButton=_filterButton;
@property(retain, nonatomic) UILabel *mirrorTipLabel; // @synthesize mirrorTipLabel=_mirrorTipLabel;
@property(retain, nonatomic) MMUIButton *mirrorButton; // @synthesize mirrorButton=_mirrorButton;
@property(retain, nonatomic) UILabel *switchCameraTipLabel; // @synthesize switchCameraTipLabel=_switchCameraTipLabel;
@property(retain, nonatomic) MMUIButton *switchCameraButton; // @synthesize switchCameraButton=_switchCameraButton;
@property(retain, nonatomic) MMUIButton *backgroundExitButton; // @synthesize backgroundExitButton=_backgroundExitButton;
@property(retain, nonatomic) UIView *panelView; // @synthesize panelView=_panelView;
@property(retain, nonatomic) MMLiveTaskId *taskId; // @synthesize taskId=_taskId;
@property(nonatomic) __weak id <MMLiveCameraOperationPanelDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (_Bool)isPureAudioModeAvailable;
- (_Bool)isCameraClosed;
- (void)onClickCameraButton;
- (void)onClickBeautyButton;
- (void)onClickFilterButton;
- (void)onClickMirrorButton;
- (void)onClickSwitchCameraButton;
- (void)closeWithNextState:(unsigned long long)arg1;
- (void)onTapNotPanelArea;
- (void)updateButtonStatesForPureAudioMode:(_Bool)arg1;
- (void)checkAndUpdateCameraButtonState:(_Bool)arg1;
- (void)checkAndUpdateMirrorButtonState;
- (void)updateMirrorButtonIsMirrored:(_Bool)arg1;
- (id)getLiveTask;
- (void)closePanelDirectly;
- (void)showPanel;
- (void)updatePanelViews;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 andTaskId:(id)arg2;

@end

