//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IMusicMVPostDataServiceExt-Protocol.h"
#import "MMMVPlayerDelegate-Protocol.h"
#import "MMMusicAlbumRtnExt-Protocol.h"
#import "MMMusicLiveCGIMgrDelegate-Protocol.h"
#import "MMMusicLiveCommentLikeOperationHandler-Protocol.h"
#import "MMMusicLiveViewControllerDelegate-Protocol.h"
#import "MMMusicLyricsRtnExt-Protocol.h"
#import "MMMusicMVEditorViewControllerDelegate-Protocol.h"
#import "MMMusicMVMiniTransitionControllerDelegate-Protocol.h"
#import "MMMusicMVPlayerBgViewDelegate-Protocol.h"
#import "MMMusicMVRecommendViewControllerDataSource-Protocol.h"
#import "MMMusicMVSwitchNewAnimatorDelegate-Protocol.h"
#import "MMMusicVCCacheMgrProtocol-Protocol.h"
#import "MMMusicViewSharingTransitionAdaptedViewController-Protocol.h"
#import "MusicLinkServiceExtension-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCFinderCommentDetailViewControllerDelegate-Protocol.h"
#import "WCFinderDataItemExt-Protocol.h"
#import "WCFinderFeedContentVMExt-Protocol.h"

@class MMMVPlayer, MMMusicInfo, MMMusicLiveBaseMsg, MMMusicLiveCGIMgr, MMMusicLiveViewController, MMMusicMVEditorViewController, MMMusicMVMiniTransitionController, MMMusicMVRecommendViewController, MMMusicMVSwitchNewAnimator, MMMusicVCOpenParams, NSArray, NSMutableArray, NSString, UIPanGestureRecognizer, UIView, UIViewController, WCFinderFeedContentVM;

@interface MMMusicViewController : MMUIViewController <MMMusicMVMiniTransitionControllerDelegate, MMMusicAlbumRtnExt, MMMusicLyricsRtnExt, MMMusicLiveViewControllerDelegate, MMMusicMVEditorViewControllerDelegate, MMMusicMVPlayerBgViewDelegate, MMMusicLiveCGIMgrDelegate, MMMusicLiveCommentLikeOperationHandler, WCActionSheetDelegate, MMMusicViewSharingTransitionAdaptedViewController, IMusicMVPostDataServiceExt, WCFinderCommentDetailViewControllerDelegate, WCFinderFeedContentVMExt, MMMusicMVRecommendViewControllerDataSource, WCFinderDataItemExt, MMMVPlayerDelegate, MMMusicMVSwitchNewAnimatorDelegate, UIGestureRecognizerDelegate, MusicLinkServiceExtension, MMMusicVCCacheMgrProtocol>
{
    unsigned int m_uiCreateTime;
    _Bool m_hasPushedSystemInfo;
    unsigned int m_currentAudienceCount;
    MMMusicLiveCGIMgr *_cgiMgr;
    _Bool m_isSliding;
    double m_curMusicTimeInMs;
    double m_curMusicTimeInMsWhenBeginDragging;
    MMMusicVCOpenParams *_openParams;
    _Bool _bResumeMusicAfterBackFrom3rdApp;
    MMMusicLiveBaseMsg *_tappedBaseMsg;
    _Bool _bAppear;
    _Bool _isLoadingRecommendedModels;
    WCFinderFeedContentVM *_commentFinderFeedContentVM;
    double _pauseAtPosWhenAppearInNestingFeature;
    UIPanGestureRecognizer *_switchMvGes;
    MMMusicMVSwitchNewAnimator *_switchAnimator;
    _Bool _isModelSwitchAnimating;
    _Bool _hasRequestedDataForEmptyMV;
    _Bool _hasRequestedPermissionAndJoin;
    _Bool _hasRequestedDataAfterModelRequested;
    _Bool _hasFinishedMVModelRequest;
    _Bool _isOpeningCommentList;
    _Bool _hasGetSongStatusResponse;
    _Bool _hasPouredMusicFeedStart;
    _Bool _hasRequestedGetBeatTrack;
    _Bool _markedVideoOffsetDirty;
    _Bool _wasConsumedEditor;
    _Bool _wasConsumedComment;
    _Bool _wasConsumedSlider;
    _Bool _notFirstReload;
    _Bool _isDragOrClickLyrics;
    _Bool _pausedManually;
    _Bool _hasChargeForSong;
    _Bool _isMinimized;
    MMMusicInfo *_musicInfo;
    MMMusicMVMiniTransitionController *_transitionController;
    NSString *_chatRoomSongId;
    NSString *_songId;
    UIViewController *_currentTopViewController;
    NSMutableArray *_recommendedModels;
    MMMusicLiveViewController *_liveViewController;
    MMMusicMVEditorViewController *_editorViewController;
    NSString *_curVideoUsrName;
    NSMutableArray *_onlineCountInfos;
    double _lastStartRecordOnlineCountTimestamp;
    unsigned long long _maxOnlineCount;
    unsigned long long _minOnlineCount;
    double _lastTotalDuration;
    double _lastStartTimestamp;
    unsigned long long _clickCommentCount;
    double _lastMVTotalDuration;
    double _lastMVStartTimestamp;
    unsigned long long _clickProfileCount;
    unsigned long long _clickQuoteProfileCount;
    unsigned long long _stopMusicCount;
    unsigned long long _enterLyricsPageCount;
    double _lyricsPageDuration;
    double _lyricsPageStartTimestamp;
    MMMVPlayer *_mvPlayer;
    MMMusicMVRecommendViewController *_mvRecommendViewController;
    UIView *_swipeAnimationToView;
    NSArray *_getBeatTrackRespArrTrackItem;
    NSArray *_getBeatTrackRespArrFlexBasicClipTrackItem;
    NSString *_taskBizKey;
    unsigned long long _exitType;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long exitType; // @synthesize exitType=_exitType;
@property(nonatomic) _Bool isMinimized; // @synthesize isMinimized=_isMinimized;
@property(retain, nonatomic) NSString *taskBizKey; // @synthesize taskBizKey=_taskBizKey;
@property(retain, nonatomic) NSArray *getBeatTrackRespArrFlexBasicClipTrackItem; // @synthesize getBeatTrackRespArrFlexBasicClipTrackItem=_getBeatTrackRespArrFlexBasicClipTrackItem;
@property(retain, nonatomic) NSArray *getBeatTrackRespArrTrackItem; // @synthesize getBeatTrackRespArrTrackItem=_getBeatTrackRespArrTrackItem;
@property(nonatomic) _Bool hasChargeForSong; // @synthesize hasChargeForSong=_hasChargeForSong;
@property(nonatomic) _Bool pausedManually; // @synthesize pausedManually=_pausedManually;
@property(retain, nonatomic) UIView *swipeAnimationToView; // @synthesize swipeAnimationToView=_swipeAnimationToView;
@property(retain, nonatomic) MMMusicMVRecommendViewController *mvRecommendViewController; // @synthesize mvRecommendViewController=_mvRecommendViewController;
@property(retain, nonatomic) MMMVPlayer *mvPlayer; // @synthesize mvPlayer=_mvPlayer;
@property(nonatomic) double lyricsPageStartTimestamp; // @synthesize lyricsPageStartTimestamp=_lyricsPageStartTimestamp;
@property(nonatomic) double lyricsPageDuration; // @synthesize lyricsPageDuration=_lyricsPageDuration;
@property(nonatomic) _Bool isDragOrClickLyrics; // @synthesize isDragOrClickLyrics=_isDragOrClickLyrics;
@property(nonatomic) unsigned long long enterLyricsPageCount; // @synthesize enterLyricsPageCount=_enterLyricsPageCount;
@property(nonatomic) unsigned long long stopMusicCount; // @synthesize stopMusicCount=_stopMusicCount;
@property(nonatomic) unsigned long long clickQuoteProfileCount; // @synthesize clickQuoteProfileCount=_clickQuoteProfileCount;
@property(nonatomic) unsigned long long clickProfileCount; // @synthesize clickProfileCount=_clickProfileCount;
@property(nonatomic) _Bool notFirstReload; // @synthesize notFirstReload=_notFirstReload;
@property(nonatomic) _Bool wasConsumedSlider; // @synthesize wasConsumedSlider=_wasConsumedSlider;
@property(nonatomic) double lastMVStartTimestamp; // @synthesize lastMVStartTimestamp=_lastMVStartTimestamp;
@property(nonatomic) double lastMVTotalDuration; // @synthesize lastMVTotalDuration=_lastMVTotalDuration;
@property(nonatomic) unsigned long long clickCommentCount; // @synthesize clickCommentCount=_clickCommentCount;
@property(nonatomic) _Bool wasConsumedComment; // @synthesize wasConsumedComment=_wasConsumedComment;
@property(nonatomic) _Bool wasConsumedEditor; // @synthesize wasConsumedEditor=_wasConsumedEditor;
@property(nonatomic) double lastStartTimestamp; // @synthesize lastStartTimestamp=_lastStartTimestamp;
@property(nonatomic) double lastTotalDuration; // @synthesize lastTotalDuration=_lastTotalDuration;
@property(nonatomic) unsigned long long minOnlineCount; // @synthesize minOnlineCount=_minOnlineCount;
@property(nonatomic) unsigned long long maxOnlineCount; // @synthesize maxOnlineCount=_maxOnlineCount;
@property(nonatomic) double lastStartRecordOnlineCountTimestamp; // @synthesize lastStartRecordOnlineCountTimestamp=_lastStartRecordOnlineCountTimestamp;
@property(retain, nonatomic) NSMutableArray *onlineCountInfos; // @synthesize onlineCountInfos=_onlineCountInfos;
@property(nonatomic) _Bool markedVideoOffsetDirty; // @synthesize markedVideoOffsetDirty=_markedVideoOffsetDirty;
@property(nonatomic) _Bool hasRequestedGetBeatTrack; // @synthesize hasRequestedGetBeatTrack=_hasRequestedGetBeatTrack;
@property(nonatomic) _Bool hasPouredMusicFeedStart; // @synthesize hasPouredMusicFeedStart=_hasPouredMusicFeedStart;
@property(nonatomic) _Bool hasGetSongStatusResponse; // @synthesize hasGetSongStatusResponse=_hasGetSongStatusResponse;
@property(nonatomic) _Bool isOpeningCommentList; // @synthesize isOpeningCommentList=_isOpeningCommentList;
@property(nonatomic) _Bool hasFinishedMVModelRequest; // @synthesize hasFinishedMVModelRequest=_hasFinishedMVModelRequest;
@property(nonatomic) _Bool hasRequestedDataAfterModelRequested; // @synthesize hasRequestedDataAfterModelRequested=_hasRequestedDataAfterModelRequested;
@property(nonatomic) _Bool hasRequestedPermissionAndJoin; // @synthesize hasRequestedPermissionAndJoin=_hasRequestedPermissionAndJoin;
@property(nonatomic) _Bool hasRequestedDataForEmptyMV; // @synthesize hasRequestedDataForEmptyMV=_hasRequestedDataForEmptyMV;
@property(retain, nonatomic) NSString *curVideoUsrName; // @synthesize curVideoUsrName=_curVideoUsrName;
@property(nonatomic) _Bool isModelSwitchAnimating; // @synthesize isModelSwitchAnimating=_isModelSwitchAnimating;
@property(retain, nonatomic) MMMusicMVEditorViewController *editorViewController; // @synthesize editorViewController=_editorViewController;
@property(retain, nonatomic) MMMusicLiveViewController *liveViewController; // @synthesize liveViewController=_liveViewController;
@property(retain, nonatomic) NSMutableArray *recommendedModels; // @synthesize recommendedModels=_recommendedModels;
@property(retain, nonatomic) UIViewController *currentTopViewController; // @synthesize currentTopViewController=_currentTopViewController;
@property(retain, nonatomic) NSString *songId; // @synthesize songId=_songId;
@property(retain, nonatomic) NSString *chatRoomSongId; // @synthesize chatRoomSongId=_chatRoomSongId;
@property(retain, nonatomic) MMMusicMVMiniTransitionController *transitionController; // @synthesize transitionController=_transitionController;
@property(retain, nonatomic) MMMusicInfo *musicInfo; // @synthesize musicInfo=_musicInfo;
- (void)onDidStartAnim:(_Bool)arg1 extDict:(id)arg2;
- (void)handleNestingFeatureWithState:(unsigned long long)arg1 musicInfo:(id)arg2 errInfo:(id)arg3;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (id)blurCoverViewWithModel:(id)arg1;
- (void)onPanHorizontalWithPercent:(double)arg1 isFinish:(_Bool)arg2;
- (void)handlePanGes:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)onFinderDataItemCommentLikeStatusChangeWithTid:(id)arg1 commentID:(unsigned long long)arg2 rootCommentID:(unsigned long long)arg3 likeStatus:(_Bool)arg4;
- (void)onFinderDataItemDeleteComment:(id)arg1 rootCommentID:(unsigned long long)arg2 tid:(id)arg3;
- (void)onFinderDataItemPostComment:(id)arg1 tid:(id)arg2;
- (void)onMusicLiveMVLikeWithMVModel:(id)arg1 isSuccess:(_Bool)arg2;
- (void)onFeedContent:(id)arg1 commentDataChanged:(id)arg2;
- (void)setPushedFromType:(unsigned long long)arg1;
- (void)clickCommentNickname:(id)arg1 username:(id)arg2 contact:(id)arg3 isWeChatFriend:(_Bool)arg4 dataItem:(id)arg5;
- (void)reportFullStatsImmediately;
- (void)pourForwardStat;
- (void)pourMusicFeedStartStat;
@property(readonly) _Bool isMVRecommendListLoading;
@property(readonly) NSArray *mvModelsForMVRecommendedViewController;
@property(readonly) unsigned long long totalMVModelsCountForMVRecommendedViewController;
- (void)onStartFinishAnimBToNext:(_Bool)arg1 extDict:(id)arg2;
- (void)onMVPostDataServicePostMVFailedWithLocalId:(id)arg1;
- (void)onMVPostDataServicePostMVSuccess:(id)arg1 svrDataItem:(id)arg2 localId:(id)arg3 relatedDraftId:(id)arg4;
- (void)onMusicLiveCheckPermissionRsp:(id)arg1 result:(id)arg2;
- (void)onMusicLiveGetSongStatusWithIsSuccess:(_Bool)arg1 resp:(id)arg2;
- (void)onMusicMVCGISerivceGetMvInfoFailWithObjectId:(unsigned long long)arg1 failureType:(unsigned long long)arg2 errMsg:(id)arg3;
- (void)onMusicMVCGISerivceGetMvInfoSuccessWithMVModel:(id)arg1 objectId:(unsigned long long)arg2;
- (void)onMusicPlayStatusChanged;
- (void)onMusicPlayInnerStatusChanged:(unsigned long long)arg1 musicInfo:(id)arg2 errInfo:(id)arg3;
- (void)deleteCurrentMV;
- (void)doLikeMVOperation:(_Bool)arg1;
- (void)updateCurrentVideoFinderAuthorInfo;
- (void)switchToMVModelAnimated:(id)arg1 directionIsLeft:(_Bool)arg2 scene:(unsigned long long)arg3;
- (void)reloadDataWithMVModel:(id)arg1 seekToStart:(_Bool)arg2 scene:(unsigned long long)arg3;
- (void)reloadDataWithMVModel:(id)arg1 seekToStart:(_Bool)arg2 scene:(unsigned long long)arg3 showDefaultImage:(_Bool)arg4;
- (void)reqGetBeatTrackIfNeed;
- (void)requestRecommendedList;
- (void)requestDurationRequiredDataIfAvailable;
- (void)setInteractivePopEnabled:(_Bool)arg1;
- (id)currUinNickName;
- (id)currUin;
- (void)reloadWithGetBeatTrackRespIfNeed;
- (void)onMusicLiveGetBeatTracks:(id)arg1 arrFlexBasicClipTrack:(id)arg2;
- (void)onMusicLiveGetMVRecommentList:(id)arg1 continueFlag:(_Bool)arg2 requestId:(id)arg3;
- (void)onMusicLivePostMsgIsSuccess:(_Bool)arg1 newMsg:(id)arg2 songId:(id)arg3 errMsg:(id)arg4;
- (void)onMusicLiveGetHotMsgList:(id)arg1 songId:(id)arg2;
- (void)updateOnlineCount:(unsigned int)arg1;
- (void)onMusicLiveHeartBeatRespWithOnlineCount:(unsigned int)arg1 songId:(id)arg2 bSuccess:(_Bool)arg3;
- (void)onMusicLiveJoinWithSongId:(id)arg1 isSuccess:(_Bool)arg2;
- (void)onMVEditorViewControllerCreatedMVFinished:(id)arg1 isDraft:(_Bool)arg2;
- (void)checkVideoStatus:(unsigned int)arg1;
- (_Bool)shouldPlayVideo;
- (void)updateUIWhenEndDragging;
- (void)updateUIWhenBeginDragging;
- (void)onGetBeatTrackIfNeed;
- (void)onClickMinimize;
- (void)onClickClose;
- (void)onLiveRoomLongPressAndExpose:(id)arg1;
- (void)onLiveRoomLongPressAndCopy:(id)arg1;
- (void)onExitLyricsPage:(_Bool)arg1;
- (void)onEnterLyricsPage;
- (void)onDeleteMVExposed;
- (void)onShareActionSuccess;
- (void)onLiveVCTransitToMVWithMsg:(id)arg1;
- (void)onLiveVCSendCommentWithContent:(id)arg1;
- (void)onShareToFriends:(id)arg1 withSource:(unsigned long long)arg2;
- (void)onLiveVCAddFavWithSource:(unsigned long long)arg1;
- (void)onShareToWcWithSource:(unsigned long long)arg1;
- (void)onOpenMusicInfo;
- (void)onOpenStatusSettingWithSource:(unsigned long long)arg1;
- (void)onOpen3rdMusicAppWithType:(unsigned long long)arg1 source:(unsigned long long)arg2;
- (id)mvOperationUrlForStatistics;
- (void)onToggleLikeMVStatus;
- (void)onClickComment;
- (void)openCommentListWithRefCommentID:(unsigned long long)arg1;
- (void)onClickRetryPostMV;
- (void)onClickDeleteMV;
- (void)onClickClearContent;
- (void)onClickCreateMV:(unsigned long long)arg1;
- (void)onLiveVCMusicResume:(double)arg1;
- (void)onLiveVCMusicPause:(double)arg1;
- (void)onLiveVCMusicSliderDidSeek:(double)arg1;
- (void)onLiveVCMusicSliderProgressChanged:(double)arg1 isSliding:(_Bool)arg2;
- (void)OnGetLyrics:(id)arg1 Lyrics:(id)arg2;
- (void)onPageScroll;
- (void)musicMVPlayerOnHorizontalSwipeWithDirection:(_Bool)arg1;
- (void)musicMVPlayerOnHideBufferingView;
- (void)musicMVPlayerOnShowBufferingView;
- (void)onClickOpenRecommendedMVList;
- (void)musicMVPlayerOnLongPress;
- (void)musicMVPlayerOnLikeWithGestureRecognizer:(id)arg1 inView:(id)arg2;
- (void)musicMVPlayerOnLikeOperation;
- (_Bool)onShouldMenuShowComplain;
- (id)onLiveVCGetMusicShareItem;
- (void)onAuthorInfoViewClickSwitch;
- (void)onAuthorInfoViewClickFinderHitLabel;
- (void)onAuthorInfoViewClickMVNickName;
- (void)onAuthorInfoViewClickMVAvatar;
- (_Bool)isEnterFromFinder;
- (void)pushFinderProfileWithUsername:(id)arg1;
- (void)musicMVPlayerOnClickMVHeadImg;
- (void)musicMVPlayerOnClickMVNickname;
- (void)musicMVPlayerOnVideoToggleJumpFinderProfileOperation:(id)arg1;
- (void)musicMVPlayerOnTappedVideo;
- (void)musicMVPlayerOnVideoTogglePostOperation;
- (void)muiscMVPlayerOnTryPostVideo;
- (void)musicMVPlayerWillDisplayEpisodeView:(id)arg1 ofIndex:(unsigned long long)arg2;
- (void)startPlayWithModel:(id)arg1;
- (void)musicLinkService:(id)arg1 didGetLinkWithResults:(id)arg2;
- (void)MVPlayer:(id)arg1 onMusicProgressUpdate:(double)arg2 totalDuration:(double)arg3;
- (void)reqDataAfterGetMVModel;
- (void)musicMVPlayerWillBeginDragging;
- (double)currentMusicTimeOffsetInMs;
- (void)reqDataForEmptyMV;
- (void)reqCheckPermissionAndJoin;
- (_Bool)mvPlayerShouldPlayVideo:(id)arg1;
- (void)MVPlayer:(id)arg1 onMusicDurationAvailable:(double)arg2;
- (void)MVPlayer:(id)arg1 didUpdateEpisodeIndexFrom:(unsigned int)arg2 toIndex:(unsigned int)arg3;
- (_Bool)handleErrorState:(unsigned long long)arg1 musicInfo:(id)arg2 errInfo:(id)arg3;
- (void)viewDidLayoutSubviews;
- (void)appWillEnterForeground:(id)arg1;
- (void)viewDidBePopedOrDismissed:(_Bool)arg1;
- (void)viewDidBePushOrPresent:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)playCurMusicWhenAppear;
- (_Bool)useTransparentNavibar;
- (void)initData;
- (void)initView;
- (_Bool)hasActiveMusicVCInCurNavVC;
- (_Bool)shouldInteractivePop;
- (void)viewWillBeDismissed:(_Bool)arg1;
- (void)viewDidLoad;
- (void)onStatExitMVPlayer;
- (void)onStatEnterMVPlayer:(_Bool)arg1;
- (double)mvTotalDuration;
- (double)totalDuration;
- (id)initWithOpenParams:(id)arg1;
- (void)dealloc;
- (id)sessionID;
- (void)handleMVEditorViewControllerCreatedMVFinished:(id)arg1 isDraft:(_Bool)arg2 fromOpenParams:(id)arg3;
- (id)mmNavigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (id)mmNavigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)maximizeTransitionDidEnd;
- (void)minimizationSystemPopTransitionDidEnd:(_Bool)arg1;
- (void)minimizationTransitionDidEnd:(_Bool)arg1;
- (_Bool)shouldBlockMinimizationEntryInInteractivePop;
- (id)minimizationInteractivePopGetPendingTaskContextWithGenerateType:(unsigned long long)arg1;
- (id)minimizationTaskData;
- (void)minimizationInteractivePopToMinimizeTask:(_Bool)arg1;
- (void)minimizationInteractivePopGestureRecognizerDidBegin;
- (void)hideOrShowVisibleCellVideoPlayerView:(_Bool)arg1;
- (void)transitToViewController:(id)arg1 animator:(id)arg2 beforeTransition:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setupLiveViewControllerIfNeeded;
- (id)defaultTransitionAnimator;
- (void)presentEditorViewControllerFromScene:(unsigned long long)arg1;
- (void)transitToLiveViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

