//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMBadgeView, MMTabbarItem, MMWebImageView, UILabel;

@interface MMTabBarItemView : UIView
{
    _Bool _isSelected;
    MMTabbarItem *_item;
    long long _unreadCount;
    MMWebImageView *_imageView;
    UILabel *_textLabel;
    MMBadgeView *_badgeView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMBadgeView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) MMWebImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) long long unreadCount; // @synthesize unreadCount=_unreadCount;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) MMTabbarItem *item; // @synthesize item=_item;
- (void)preloadURLImages;
- (void)reloadIconImage;
- (void)relayoutIconAndBadge;
- (void)setSelected:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setupUI;
- (struct CGPoint)normalBadgeOrigin;
- (double)getBadgeViewRightMarginPortrait;
- (void)showTabBarSingleBadge;
- (void)setTabBarBadgeImage:(id)arg1;
- (void)setTabBarBadgeValue:(long long)arg1;
- (void)setBadgeViewHidden:(_Bool)arg1;
- (void)setTitle:(id)arg1;
- (id)initWithItem:(id)arg1 frame:(struct CGRect)arg2;

@end

