//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSDictionary, NSString;

@interface MMWebPrefetchDownloadTaskRequest : MMObject
{
    _Bool _isUsingSingtonVM;
    unsigned int _requestId;
    unsigned int _scene;
    unsigned int _subScene;
    NSString *_url;
    NSDictionary *_requestHeader;
    NSString *_pathForRespHeader;
    NSString *_pathForRespData;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isUsingSingtonVM; // @synthesize isUsingSingtonVM=_isUsingSingtonVM;
@property(nonatomic) unsigned int subScene; // @synthesize subScene=_subScene;
@property(nonatomic) unsigned int scene; // @synthesize scene=_scene;
@property(copy, nonatomic) NSString *pathForRespData; // @synthesize pathForRespData=_pathForRespData;
@property(copy, nonatomic) NSString *pathForRespHeader; // @synthesize pathForRespHeader=_pathForRespHeader;
@property(retain, nonatomic) NSDictionary *requestHeader; // @synthesize requestHeader=_requestHeader;
@property(nonatomic) unsigned int requestId; // @synthesize requestId=_requestId;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;

@end

