//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString, UIColor, UIImage;

@interface MMWebViewCustomNavigationBarItemState : MMObject
{
    _Bool _isRightBarItemJSApiDefined;
    _Bool _isRightBarItemHidden;
    _Bool _disableMinimizeBlock;
    NSString *_rightBarItemTitle;
    UIColor *_rightBarItemTintColor;
    UIImage *_rightBarItemIconImage;
    CDUnknownBlockType _rightBarItemClickCallBack;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool disableMinimizeBlock; // @synthesize disableMinimizeBlock=_disableMinimizeBlock;
@property(nonatomic) _Bool isRightBarItemHidden; // @synthesize isRightBarItemHidden=_isRightBarItemHidden;
@property(copy, nonatomic) CDUnknownBlockType rightBarItemClickCallBack; // @synthesize rightBarItemClickCallBack=_rightBarItemClickCallBack;
@property(retain, nonatomic) UIImage *rightBarItemIconImage; // @synthesize rightBarItemIconImage=_rightBarItemIconImage;
@property(retain, nonatomic) UIColor *rightBarItemTintColor; // @synthesize rightBarItemTintColor=_rightBarItemTintColor;
@property(copy, nonatomic) NSString *rightBarItemTitle; // @synthesize rightBarItemTitle=_rightBarItemTitle;
@property(nonatomic) _Bool isRightBarItemJSApiDefined; // @synthesize isRightBarItemJSApiDefined=_isRightBarItemJSApiDefined;
- (_Bool)shouldBlockMinimization;

@end

