//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MMWebViewMpInfoModelVideoInfo : NSObject
{
    unsigned int _videoWidth;
    unsigned int _videoHeight;
    unsigned int _duration;
    NSString *_vid;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int duration; // @synthesize duration=_duration;
@property(nonatomic) unsigned int videoHeight; // @synthesize videoHeight=_videoHeight;
@property(nonatomic) unsigned int videoWidth; // @synthesize videoWidth=_videoWidth;
@property(copy, nonatomic) NSString *vid; // @synthesize vid=_vid;

@end

