//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSData, NSMutableArray, NSString;

@interface MsgOptions : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *atList; // @dynamic atList;
@property(retain, nonatomic) NSData *cliLocalData; // @dynamic cliLocalData;
@property(retain, nonatomic) NSString *complaintUrl; // @dynamic complaintUrl;
@property(nonatomic) unsigned int msgBizType; // @dynamic msgBizType;

@end

