//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUserService.h"

#import "AVVideoDataSource-Protocol.h"
#import "AVVideoDeviceDelegate-Protocol.h"
#import "AVVideoDeviceSessionDelegate-Protocol.h"
#import "AVVideoDeviceSetupSessionDelegate-Protocol.h"
#import "CNetworkStatusExt-Protocol.h"
#import "IContactMgrExt-Protocol.h"
#import "IGroupMgrExt-Protocol.h"
#import "IMinimizeTaskDelegateInterface-Protocol.h"
#import "IMsgExt-Protocol.h"
#import "ISysCallCheckExt-Protocol.h"
#import "MMKernelExt-Protocol.h"
#import "MMServiceProtocol-Protocol.h"
#import "MMViewCaptureDelegate-Protocol.h"
#import "MonoServiceMsgDelegate-Protocol.h"
#import "MonoServiceMsgLogicDelegate-Protocol.h"
#import "MultiTalkCgiDelegate-Protocol.h"
#import "MultiTalkMainViewControllerDelegate-Protocol.h"
#import "MultitalkApiDelegate-Protocol.h"
#import "MultitalkMinimizeWindowDelegate-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"
#import "VoIPPushKitExt-Protocol.h"
#import "WXCAssistHelperDelegate-Protocol.h"
#import "WXCMultiTalkApiDelegate-Protocol.h"

@class AVAudioPlayer, AVVideoDevice, MMTimer, MMViewCapture, MinimizeTaskData, MultiTalkMainViewController, MultiTalkWindow, MultitalkMinimizeView, MultitalkMinimizeWindow, NSMutableArray, NSMutableDictionary, NSRecursiveLock, NSString, RingBackSoundCoordinator, SafeMutableDictionary, VoipCheckAudioDeviceObj;

@interface MultiTalkMgr : MMUserService <MMKernelExt, MultitalkApiDelegate, WXCMultiTalkApiDelegate, WXCAssistHelperDelegate, MultiTalkCgiDelegate, IMsgExt, MultiTalkMainViewControllerDelegate, MultitalkMinimizeWindowDelegate, AVVideoDeviceSessionDelegate, AVVideoDeviceDelegate, AVVideoDataSource, AVVideoDeviceSetupSessionDelegate, MMViewCaptureDelegate, CNetworkStatusExt, ISysCallCheckExt, MonoServiceMsgLogicDelegate, MonoServiceMsgDelegate, VoIPPushKitExt, IGroupMgrExt, IContactMgrExt, IMinimizeTaskDelegateInterface, PBMessageObserverDelegate, MMServiceProtocol>
{
    struct __CVBuffer *rotatedBuffer;
    char *cameraBuf;
    int cameraBufSize;
    _Bool _isMicrophoneOn;
    _Bool _isSpeakerEnabled;
    _Bool _isSpeakerOn;
    _Bool _isCameraEnabled;
    _Bool _isCameraOn;
    _Bool _m_videoDeviceRunning;
    _Bool _m_multiTalkReady;
    _Bool _m_isCalling;
    _Bool _m_deviceLaunchSuccess;
    _Bool _isCameraSwitchingOn;
    _Bool _isScreenOn;
    _Bool _isScreenSwitchingOn;
    _Bool _m_blockDisplayVideo;
    _Bool _m_useLowQualityVideo;
    _Bool _m_haveBigVideoSubscriber;
    _Bool _isMinimizeMode;
    unsigned int _currentMessageId;
    unsigned int _m_uploadFpsCount;
    unsigned int _m_nextCanJoinTalkTime;
    unsigned int _m_nextCanCreateTalkTime;
    int _lastSubscribeScreenMemberID;
    unsigned int _m_nextCanOpenCameraTime;
    NSMutableArray *m_cgiList;
    MultiTalkWindow *m_mainWindow;
    MultitalkMinimizeWindow *m_statusWindow;
    NSMutableDictionary *__currentSDKModeList;
    SafeMutableDictionary *_m_renderDic;
    SafeMutableDictionary *_m_videoInfoDic;
    AVVideoDevice *_m_videoDevice;
    AVAudioPlayer *_m_audioPlayer;
    RingBackSoundCoordinator *_ringCoordinator;
    MMViewCapture *_viewCapture;
    long long _lastOrientationFromViewCapture;
    NSMutableDictionary *_validatingScreenSharingMapping;
    MMTimer *_m_uploadFpsTimer;
    NSMutableDictionary *_m_bannerInfoList;
    NSString *_m_talkingGroupId;
    NSMutableDictionary *_m_lastBannerTsList;
    NSMutableDictionary *_m_invitedFlagList;
    NSString *_m_lastSubscribeName;
    NSString *_lastSubscribeScreenUserName;
    MinimizeTaskData *_minimizeTaskData;
    MultitalkMinimizeView *_minimizeView;
    VoipCheckAudioDeviceObj *_checkAudioDeviceObj;
    MultiTalkMainViewController *_mainViewController;
    NSRecursiveLock *_m_videoEncLock;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSRecursiveLock *m_videoEncLock; // @synthesize m_videoEncLock=_m_videoEncLock;
@property(nonatomic) __weak MultiTalkMainViewController *mainViewController; // @synthesize mainViewController=_mainViewController;
@property(retain, nonatomic) VoipCheckAudioDeviceObj *checkAudioDeviceObj; // @synthesize checkAudioDeviceObj=_checkAudioDeviceObj;
@property(nonatomic) _Bool isMinimizeMode; // @synthesize isMinimizeMode=_isMinimizeMode;
@property(retain, nonatomic) MultitalkMinimizeView *minimizeView; // @synthesize minimizeView=_minimizeView;
@property(retain, nonatomic) MinimizeTaskData *minimizeTaskData; // @synthesize minimizeTaskData=_minimizeTaskData;
@property(nonatomic) unsigned int m_nextCanOpenCameraTime; // @synthesize m_nextCanOpenCameraTime=_m_nextCanOpenCameraTime;
@property(nonatomic) int lastSubscribeScreenMemberID; // @synthesize lastSubscribeScreenMemberID=_lastSubscribeScreenMemberID;
@property(copy, nonatomic) NSString *lastSubscribeScreenUserName; // @synthesize lastSubscribeScreenUserName=_lastSubscribeScreenUserName;
@property(retain, nonatomic) NSString *m_lastSubscribeName; // @synthesize m_lastSubscribeName=_m_lastSubscribeName;
@property(nonatomic) _Bool m_haveBigVideoSubscriber; // @synthesize m_haveBigVideoSubscriber=_m_haveBigVideoSubscriber;
@property(nonatomic) unsigned int m_nextCanCreateTalkTime; // @synthesize m_nextCanCreateTalkTime=_m_nextCanCreateTalkTime;
@property(nonatomic) unsigned int m_nextCanJoinTalkTime; // @synthesize m_nextCanJoinTalkTime=_m_nextCanJoinTalkTime;
@property(retain, nonatomic) NSMutableDictionary *m_invitedFlagList; // @synthesize m_invitedFlagList=_m_invitedFlagList;
@property(retain, nonatomic) NSMutableDictionary *m_lastBannerTsList; // @synthesize m_lastBannerTsList=_m_lastBannerTsList;
@property(retain, nonatomic) NSString *m_talkingGroupId; // @synthesize m_talkingGroupId=_m_talkingGroupId;
@property(retain, nonatomic) NSMutableDictionary *m_bannerInfoList; // @synthesize m_bannerInfoList=_m_bannerInfoList;
@property(nonatomic) _Bool m_useLowQualityVideo; // @synthesize m_useLowQualityVideo=_m_useLowQualityVideo;
@property(nonatomic) _Bool m_blockDisplayVideo; // @synthesize m_blockDisplayVideo=_m_blockDisplayVideo;
@property(retain, nonatomic) MMTimer *m_uploadFpsTimer; // @synthesize m_uploadFpsTimer=_m_uploadFpsTimer;
@property(nonatomic) unsigned int m_uploadFpsCount; // @synthesize m_uploadFpsCount=_m_uploadFpsCount;
@property(retain, nonatomic) NSMutableDictionary *validatingScreenSharingMapping; // @synthesize validatingScreenSharingMapping=_validatingScreenSharingMapping;
@property(nonatomic) _Bool isScreenSwitchingOn; // @synthesize isScreenSwitchingOn=_isScreenSwitchingOn;
@property(nonatomic) _Bool isScreenOn; // @synthesize isScreenOn=_isScreenOn;
@property(nonatomic) _Bool isCameraSwitchingOn; // @synthesize isCameraSwitchingOn=_isCameraSwitchingOn;
@property(nonatomic) _Bool m_deviceLaunchSuccess; // @synthesize m_deviceLaunchSuccess=_m_deviceLaunchSuccess;
@property(nonatomic) _Bool m_isCalling; // @synthesize m_isCalling=_m_isCalling;
@property(nonatomic) _Bool m_multiTalkReady; // @synthesize m_multiTalkReady=_m_multiTalkReady;
@property(nonatomic) unsigned int currentMessageId; // @synthesize currentMessageId=_currentMessageId;
@property(nonatomic) long long lastOrientationFromViewCapture; // @synthesize lastOrientationFromViewCapture=_lastOrientationFromViewCapture;
@property(retain, nonatomic) MMViewCapture *viewCapture; // @synthesize viewCapture=_viewCapture;
@property(retain, nonatomic) RingBackSoundCoordinator *ringCoordinator; // @synthesize ringCoordinator=_ringCoordinator;
@property(retain, nonatomic) AVAudioPlayer *m_audioPlayer; // @synthesize m_audioPlayer=_m_audioPlayer;
@property(nonatomic) _Bool m_videoDeviceRunning; // @synthesize m_videoDeviceRunning=_m_videoDeviceRunning;
@property(retain, nonatomic) AVVideoDevice *m_videoDevice; // @synthesize m_videoDevice=_m_videoDevice;
@property(retain, nonatomic) SafeMutableDictionary *m_videoInfoDic; // @synthesize m_videoInfoDic=_m_videoInfoDic;
@property(retain, nonatomic) SafeMutableDictionary *m_renderDic; // @synthesize m_renderDic=_m_renderDic;
@property(retain, nonatomic) NSMutableDictionary *_currentSDKModeList; // @synthesize _currentSDKModeList=__currentSDKModeList;
@property(nonatomic) _Bool isCameraOn; // @synthesize isCameraOn=_isCameraOn;
@property(nonatomic) _Bool isCameraEnabled; // @synthesize isCameraEnabled=_isCameraEnabled;
@property(nonatomic) _Bool isSpeakerOn; // @synthesize isSpeakerOn=_isSpeakerOn;
@property(nonatomic) _Bool isSpeakerEnabled; // @synthesize isSpeakerEnabled=_isSpeakerEnabled;
@property(nonatomic) _Bool isMicrophoneOn; // @synthesize isMicrophoneOn=_isMicrophoneOn;
@property(retain, nonatomic) MultitalkMinimizeWindow *m_statusWindow; // @synthesize m_statusWindow;
@property(retain, nonatomic) MultiTalkWindow *m_mainWindow; // @synthesize m_mainWindow;
@property(retain, nonatomic) NSMutableArray *m_cgiList; // @synthesize m_cgiList;
- (void)videoDevice:(id)arg1 updateFilterSetting:(id)arg2 fromABTest:(_Bool)arg3;
- (void)notifyWithData:(id)arg1;
- (void)reportMultiTalkVoipIncomingCallLogWithActionCode:(unsigned int)arg1;
- (int)valueFromScreenSharingOrientation:(long long)arg1;
- (void)didCaptureViewWithVideoBuffer:(struct CGContext *)arg1 orientation:(long long)arg2;
- (void)viewCapture:(id)arg1 didCaptureImageContext:(struct CGContext *)arg2 orientation:(long long)arg3;
- (void)resumeViewCapture;
- (void)pauseViewCapture;
- (void)stopViewCapture;
- (void)startViewCaptureWithView:(id)arg1;
- (void)clearViewCapture;
- (void)renewViewCapture;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)onContainerSizeDidChange:(id)arg1 fromSize:(struct CGSize)arg2 toSize:(struct CGSize)arg3;
- (void)onEnterMinimizedTask:(id)arg1 openContext:(id)arg2 taskEnterScene:(unsigned int)arg3;
- (_Bool)canUseGlobalMinimization;
- (void)updateMinimizeViewFromSize:(struct CGSize)arg1 toSize:(struct CGSize)arg2;
- (void)createMinimizeView;
- (id)getMinimizeTaskKey;
- (id)getMinimizeTaskData;
- (unsigned long long)getCurrentRoomID;
- (unsigned long long)getCurrentRoomKey;
- (id)getCurrentRoomBanner;
- (void)setCurrentSDKMode:(id)arg1 sdkMode:(int)arg2;
- (int)getCurrentSDKMode:(id)arg1;
- (void)onModifyContact:(id)arg1;
- (void)OnQuitGroup:(id)arg1;
- (void)quitMultiTalkAndClearBannerInfoWithGroupName:(id)arg1;
- (void)showMinimizeWindow;
- (void)hideMinimizeWindow;
- (_Bool)isMultiTalkMinimized;
- (id)getCurrentTalkingGroupId;
- (void)loadMultiTalkBannerInfoList;
- (id)getMultiTalkBannerItemWithGroupId:(id)arg1;
- (_Bool)deleteMultiTalkBannerItemWithGroupId:(id)arg1;
- (_Bool)insertMultiTalkBannerItem:(id)arg1;
- (void)showMultiTalkBanner:(_Bool)arg1 group:(id)arg2 roomId:(unsigned int)arg3 roomKey:(unsigned long long)arg4;
- (void)onReceiveVoIPPushInfo:(id)arg1;
- (_Bool)onMonoServiceMsgCancelWithMsg:(id)arg1;
- (_Bool)onMonoServiceMsgRejectWithMsg:(id)arg1;
- (void)onMonoServiceMsgStartWithMsg:(id)arg1;
- (_Bool)isMonoServiceCheckingServer;
- (_Bool)isMonoServiceUIWorking;
- (_Bool)isMonoServiceUIExist;
- (void)InputIsAvailableChanged:(_Bool)arg1;
- (void)EndInterruption;
- (void)BeginInterruption;
- (void)onSimCardNetTypeChange;
- (void)ReachabilityChange:(unsigned int)arg1;
- (void)updateNetworkTacticsWithNotify:(_Bool)arg1;
- (_Bool)checkLowNetworkWithNotify:(_Bool)arg1;
- (_Bool)checkHighWWanWithNotify:(_Bool)arg1;
- (_Bool)checkWiFiWithNotify:(_Bool)arg1;
- (_Bool)checkUnReachableWithNotify:(_Bool)arg1;
- (_Bool)isLowNetwork;
- (int)GetFrmType;
- (void)DidCapturedImage:(id)arg1;
- (int)VideoDevPutData:(int)arg1 frmData:(char *)arg2 imageWidth:(unsigned int)arg3 imageHeight:(unsigned int)arg4;
- (void)videoDevice:(id)arg1 didFailWithError:(id)arg2;
- (void)videoDeviceSessionFinished:(id)arg1;
- (void)videoDeviceSessionBegan:(id)arg1;
- (void)videoDeviceCameraBack:(id)arg1;
- (void)videoDeviceCameraFront:(id)arg1;
- (void)onVideoSessionSetupComplete;
- (void)onVideoSessionChangeCameraComplete;
- (void)onVideoSessionStopComplete;
- (void)onVideoSessionStartComplete;
- (void)onMultiTalkMainViewControllerHoldMultiTalkAudio;
- (void)onMultiTalkMainViewControllerResumeMultiTalkAudio;
- (void)onMultiTalkMainViewControllerRecoverVideoOn:(_Bool)arg1;
- (void)onMultiTalkMainViewControllerCloseVideoSendAndRecv;
- (void)onMultiTalkMainViewControllerResubscribe;
- (void)onMultiTalkMainViewControllerFlipCamera;
- (_Bool)onMultiTalkMainViewControllerShouldBlockReceiveVideo;
- (_Bool)onMultiTalkMainViewControllerRequestLocalVideoDeviceStatus;
- (void)onMultiTalkMainViewControllerAddNewMemberArray:(id)arg1 withGroup:(id)arg2;
- (void)onMultiTalkMainViewControllerScreenSharingDidResume;
- (void)onMultiTalkMainViewControllerScreenSharingDidPause;
- (void)onMultiTalkMainViewControllerScreenSharingDidStop;
- (void)onMultiTalkMainViewControllerScreenSharingDidStartWithView:(id)arg1;
- (void)onMultiTalkMainViewControllerVideoSelected:(_Bool)arg1;
- (void)onMultiTalkMainViewControllerClickedCollapseButtonWithNotAnimation;
- (void)onMultiTalkMainViewControllerClickedCollapseButton;
- (void)onMultiTalkMainViewControllerMicButtonSeclect:(_Bool)arg1;
- (void)onMultiTalkMainViewControllerSpeakerButtonSeclect:(_Bool)arg1;
- (void)onMultiTalkMainViewControllerCancelJoinWithGroup:(id)arg1;
- (void)onMultiTalkMainViewControllerReceiveTimeOutWithGroup:(id)arg1;
- (void)onMultiTalkMainViewControllerRejectWithGroup:(id)arg1;
- (void)onMultiTalkMainViewControllerAcceptWithGroup:(id)arg1;
- (void)onMultiTalkMainViewControllerHangupWithGroup:(id)arg1;
- (void)onMultiTalkMainViewControllerReceiveCancelCall:(id)arg1;
- (void)onMultiTalkMainViewControllerUpdateMessageWith:(id)arg1 duration:(unsigned int)arg2 messageId:(unsigned int)arg3;
- (void)onMultitalkMinimizeWindowClicked;
- (void)onMultiTalkTipsViewResumeMainWindowFromBanner;
- (void)onMultiTalkMainViewControllerExtendFromCollapseAnimationDidEnd;
- (void)onMultiTalkMainViewControllerCollapseAnimationWillStart;
- (void)onMultiTalkMainViewControllerExtendFromCollapseAnimationWillStart;
- (void)onMultiTalkMainViewControllerCollapseAnimationDidEnd;
- (void)clearMultiTalkStatus;
- (void)onMultiTalkMainViewControllerQuitAnimationDidEnd;
- (void)onMultiTalkMainViewControllerQuitAnimationWillStart;
- (struct CGRect)onMultiTalkMainViewControllerRequestMinimizeFrame;
- (const char *)notFriendNotify;
- (const char *)notifyBannerString;
- (const char *)notifyDataString;
- (const char *)notifyInviteString;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)onRespBuffer:(id)arg1 functionId:(unsigned int)arg2 seq:(unsigned int)arg3 retCode:(int)arg4;
- (id)getMultiTalkUserNameListWithPrivacy:(id)arg1;
- (void)onMultiTalkBannerChange:(id)arg1 WxGroupId:(id)arg2;
- (void)onMultiTalkBannerChange:(id)arg1;
- (void)onOtherDeviceHandleTalk:(id)arg1;
- (void)onDoScreenSharingSecurityCheck:(int)arg1 checkStatus:(int)arg2 fileMd5:(id)arg3;
- (void)onSetMultiTalkScreenSharingStatus:(int)arg1 ScreenSharingStatus:(int)arg2;
- (void)onMultiTalkNotAllowCameraLimit:(unsigned int)arg1;
- (void)onMultiTalkCreateLimit:(unsigned int)arg1;
- (void)onMultiTalkJoinLimit:(unsigned int)arg1;
- (void)onMultiTalkRedirectOk;
- (void)onVideoData:(unsigned int)arg1 Bgra:(char *)arg2 Width:(unsigned int)arg3 Height:(unsigned int)arg4 frontCamera:(_Bool)arg5 screenData:(_Bool)arg6;
- (void)OnVideoStateChange:(_Bool)arg1 VideoOn:(_Bool)arg2;
- (void)multiTalkAudioDeviceUnPlugin;
- (void)multiTalkAudioDevicePlugin;
- (void)onReceiveVideoMemberChangeMsg:(id)arg1 extArray:(id)arg2;
- (void)onReceiveSubscribeMemberChangeMsg:(int)arg1;
- (void)onMultiTalkDeviceLauchSuccess;
- (void)onReceiveMutilTalkPokerMsg;
- (void)OnSysCallNotifyInterrupt:(int)arg1;
- (void)onAddMultiTalkMemberResult:(_Bool)arg1 errorType:(int)arg2 groupInfo:(id)arg3;
- (void)onErr:(int)arg1 groupUserName:(id)arg2;
- (void)onSpeakerStateChange:(_Bool)arg1;
- (void)onMuteStateChange:(_Bool)arg1;
- (void)onMultiTalkReady;
- (void)onMemberChange:(id)arg1;
- (void)onReceiveMissMultiTalk:(id)arg1;
- (void)onInviteOrAcceptTimeout:(id)arg1;
- (void)onEnterMultiTalk:(id)arg1;
- (void)onCreateMultiTalk:(id)arg1;
- (void)onCancelCreateMultiTalk:(id)arg1;
- (void)onInviteMultiTalk:(id)arg1;
- (int)inviteUserType:(id)arg1;
- (void)stopRingSound;
- (void)playRingSoundWithVibration:(_Bool)arg1 isCaller:(_Bool)arg2;
- (void)playWhenEnterForeground;
- (void)rejectCall:(id)arg1;
- (void)sendMultiTalkRequset:(int)arg1 reqData:(id)arg2 cgiType:(int)arg3;
- (void)writeLog:(int)arg1 tag:(id)arg2 content:(id)arg3;
- (void)onPreQuit;
- (void)onAuthOK;
- (void)_handleValidateScreenSharingFileWithMD5:(id)arg1 ret:(int)arg2 fileStatus:(int)arg3;
- (void)_validateScreenSharingFileWithPath:(id)arg1 MD5:(id)arg2;
- (_Bool)validateScreenSharingFileWithPath:(id)arg1;
@property(readonly, nonatomic) _Bool canDoodleWhenShareScreen;
@property(readonly, nonatomic) _Bool canShareScreen;
- (void)setSpeakerState:(_Bool)arg1;
- (void)setMicrophoneState:(_Bool)arg1;
- (unsigned long long)maxMultiTalkMemberCount;
- (void)sendRequest:(id)arg1 Retry:(int)arg2;
- (void)createMultiTalkWithContacts:(id)arg1 withChatroomUsername:(id)arg2;
- (void)doCreateMultiTalkWithContacts:(id)arg1 withChatroomUsername:(id)arg2;
- (void)initVoipCheckAudioDeviceObj;
- (void)joinMultiTalkWithGroup:(id)arg1 roomId:(unsigned long long)arg2 roomKey:(unsigned long long)arg3;
- (void)joinMultiTalkWithGroupUserName:(id)arg1;
- (void)alertHangup;
- (void)resubscribeLargeVideo;
- (_Bool)isUserSharingScreenWithUserMemberID:(int)arg1;
- (int)getMemberIdByUserName:(id)arg1;
- (void)checkAndCancelSubscribeLargeSharedScreenDataWithGroupInfo:(id)arg1;
- (void)checkAndResubscribeLargeSharedScreenDataWithUserName:(id)arg1;
- (_Bool)subscribeGeneralVideoForUserList:(id)arg1;
- (void)subscribeLargeVideoForUser:(id)arg1 isSharedScreenData:(_Bool)arg2 isCancel:(_Bool)arg3;
- (int)engineDoMemberSelectForView:(id)arg1;
- (int)setNeedBigVideo:(_Bool)arg1 forUser:(id)arg2;
- (id)getMemberQualityInfoList:(id)arg1;
- (id)getTalkIngMember:(id)arg1;
- (id)getRenderForUsername:(id)arg1;
- (_Bool)isUsingEarDevice;
@property(readonly, nonatomic) _Bool isSpeakerSupported;
- (id)getRenderForMemberId:(unsigned int)arg1;
- (_Bool)isPhoneCalling;
- (_Bool)isMultiTalkValidWithWxGroupId:(id)arg1;
- (_Bool)isMultiTalkCalling;
- (_Bool)isMultiTalkLocalCameraActive;
- (_Bool)isMultiTalkActive;
- (_Bool)canStartANewCall;
- (void)startCgiWithFunctionId:(unsigned int)arg1 buffer:(id)arg2 seq:(unsigned int)arg3;
- (void)uploadFpsCountCheck;
- (void)stopVideoDevice;
- (void)startVideoDevice;
- (void)resetVideoDevice;
- (void)clearVideoDevice;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

