//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MultiDeviceUtility : NSObject
{
}

+ (id)generateCheckbox;
+ (_Bool)showSyncChatEntranceForIconType:(unsigned int)arg1 clientVersion:(unsigned int)arg2;
+ (id)defaultTitleForIconType:(unsigned int)arg1;
+ (id)generateLargeIconFromType:(unsigned int)arg1;
+ (id)svgIconNameFromType:(unsigned int)arg1 isLocked:(_Bool)arg2;
+ (id)svgLargeIconNameFromType:(unsigned int)arg1;

@end

