//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMTimer, MMUIButton, MMUILabel, MultiDeviceLoginInfo, UIButton, UIImageView;
@protocol MultiDeviceCardViewDelegate;

@interface MultiDeviceCardLoginContentView : UIView
{
    MultiDeviceLoginInfo *_deviceLoginInfo;
    id <MultiDeviceCardViewDelegate> _delegate;
    UIImageView *_iconImageView;
    MMUILabel *_titleLabel;
    MMUILabel *_tipsLabel;
    MMUIButton *_syncChatCheckbox;
    MMUIButton *_autoLoginCheckbox;
    UIButton *_confirmButton;
    UIButton *_cancelButton;
    long long _errorType;
    MMTimer *_timeoutTimer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMTimer *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property(nonatomic) long long errorType; // @synthesize errorType=_errorType;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) MMUIButton *autoLoginCheckbox; // @synthesize autoLoginCheckbox=_autoLoginCheckbox;
@property(retain, nonatomic) MMUIButton *syncChatCheckbox; // @synthesize syncChatCheckbox=_syncChatCheckbox;
@property(retain, nonatomic) MMUILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) MMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak id <MultiDeviceCardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MultiDeviceLoginInfo *deviceLoginInfo; // @synthesize deviceLoginInfo=_deviceLoginInfo;
- (void)onTimeout;
- (void)onTapCancelButton;
- (void)onTapConfirmButton;
- (void)reverseAutoLoginCheckbox;
- (void)onTapAutoLoginCheckbox;
- (void)onTapSyncChatCheckbox;
- (void)onLoginConfirmFailed;
- (id)getLoginConfirmInfo;
- (id)tips;
- (_Bool)enableRescanQRCode;
- (void)updateLayout;
- (void)hideAutoLoginCheckbox;
- (void)showAutoLoginCheckbox;
- (void)hideSyncChatCheckbox;
- (void)showSyncChatCheckbox;
- (void)updateContent;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

