//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface OftenReadBarShow : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int barType; // @dynamic barType;
@property(retain, nonatomic) NSString *bizUsername; // @dynamic bizUsername;
@property(nonatomic) unsigned int isDefaultIcon; // @dynamic isDefaultIcon;
@property(nonatomic) unsigned int isEarlierLive; // @dynamic isEarlierLive;
@property(nonatomic) unsigned int isGreenPoint; // @dynamic isGreenPoint;
@property(nonatomic) unsigned int isIconCache; // @dynamic isIconCache;
@property(retain, nonatomic) NSString *liveExportId; // @dynamic liveExportId;
@property(nonatomic) unsigned int liveScene; // @dynamic liveScene;
@property(nonatomic) unsigned int liveStatus; // @dynamic liveStatus;
@property(retain, nonatomic) NSString *logoUrl; // @dynamic logoUrl;
@property(nonatomic) unsigned int posReason; // @dynamic posReason;
@property(nonatomic) unsigned int rank; // @dynamic rank;
@property(nonatomic) unsigned int seqId; // @dynamic seqId;
@property(nonatomic) unsigned int showCount; // @dynamic showCount;
@property(nonatomic) unsigned int showTime; // @dynamic showTime;
@property(nonatomic) unsigned long long showTimeMs; // @dynamic showTimeMs;
@property(retain, nonatomic) NSString *syncBuf; // @dynamic syncBuf;
@property(nonatomic) unsigned int type; // @dynamic type;

@end

