//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QBaseVisualLayerManager.h"

@class NSMutableDictionary, NSString, QDataLayerConfigData, QVisCacheManager, QVisualLayerDataDownloader;

@interface QVisualLayerManager : QBaseVisualLayerManager
{
    _Bool _isAuthened;
    NSString *_apiKey;
    NSString *_configPath;
    QDataLayerConfigData *_config;
    QVisCacheManager *_cacheManager;
    NSMutableDictionary *_glOverlayDict;
    QVisualLayerDataDownloader *_engine;
}

- (void).cxx_destruct;
@property(retain, nonatomic) QVisualLayerDataDownloader *engine; // @synthesize engine=_engine;
@property(retain, nonatomic) NSMutableDictionary *glOverlayDict; // @synthesize glOverlayDict=_glOverlayDict;
@property(nonatomic) _Bool isAuthened; // @synthesize isAuthened=_isAuthened;
@property(retain, nonatomic) QVisCacheManager *cacheManager; // @synthesize cacheManager=_cacheManager;
@property(retain, nonatomic) QDataLayerConfigData *config; // @synthesize config=_config;
- (id)configPath;
- (id)apiKey;
- (_Bool)checkLayerUpdateNeeded:(id)arg1;
- (void)processVisLayerData:(id)arg1 layer:(id)arg2;
- (id)generateLayerURL:(id)arg1;
- (void)requestVisualLayerData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)isConfigContainsLayer:(id)arg1;
- (void)resetVisLayers;
- (void)startVerCheck:(id)arg1 configItem:(id)arg2;
- (void)updateAuthenticationConfig:(id)arg1;
- (void)notifyVisualLayerDataBuildComplete:(id)arg1;
- (id)convertIntColor:(int)arg1;
- (void)updateVisLayerProperty:(id)arg1 properties:(id)arg2;
- (void)loadCommonControls:(id)arg1 dict:(id)arg2;
- (id)loadVisArcLineData:(id)arg1;
- (id)loadVisLayerPointData:(id)arg1;
- (id)getPairedDataAndStyle:(id)arg1;
- (void)constructArcLineLayer:(id)arg1 layerID:(id)arg2;
- (void)constructHeatLayer:(id)arg1 layerID:(id)arg2;
- (void)constructHoneyCombLayer:(id)arg1 layerID:(id)arg2;
- (void)loadLocalCacheData:(id)arg1;
- (void)remove:(id)arg1;
- (void)add:(id)arg1 layerID:(id)arg2;
- (void)addLayer:(id)arg1;
- (void)setLayerZIndex:(id)arg1;
- (void)setLayerVisibility:(id)arg1;
- (void)setLayerOpacity:(id)arg1;
- (void)setApiKey:(id)arg1;
- (void)setConfigPath:(id)arg1;
- (id)init;
- (void)updateArcLineLayer:(id)arg1 param:(id)arg2;
- (void)updateArcLayer:(id)arg1 withDataAndStyle:(id)arg2;
- (void)loadArcLineDataAndStyle:(id)arg1 payload:(id)arg2;
- (void)setArcLineControls:(id)arg1 controls:(id)arg2;
- (void)createHoneyCombLayerOption:(id)arg1 param:(id)arg2;
- (void)updateHoneyCombLayerParam:(id)arg1 param:(id)arg2;
- (void)updateHoneyCombLayer:(id)arg1;
- (void)loadHoneyCombThemeStyle:(id)arg1 styleDict:(id)arg2;
- (void)loadHoneyCombDataAndStyle:(id)arg1 payload:(id)arg2;
- (void)setHoneyCombControls:(id)arg1 controls:(id)arg2;
- (void)loadHeatThemeStyle:(id)arg1 styleDict:(id)arg2;
- (void)loadHeatDataAndStyle:(id)arg1 payload:(id)arg2;
- (void)setHeatControls:(id)arg1 controls:(id)arg2;
- (void)updateHeatLayerParam:(id)arg1 param:(id)arg2;
- (void)updateHeatLayer:(id)arg1;

@end

