//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class EcWxaInfo, Media, NSString, SpuCategory;

@interface SpuSnapshot : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned long long paymentAmount; // @dynamic paymentAmount;
@property(retain, nonatomic) Media *primaryMedia; // @dynamic primaryMedia;
@property(nonatomic) unsigned long long productAmount; // @dynamic productAmount;
@property(nonatomic) unsigned int productCnt; // @dynamic productCnt;
@property(nonatomic) unsigned long long skuId; // @dynamic skuId;
@property(retain, nonatomic) NSString *skuName; // @dynamic skuName;
@property(retain, nonatomic) SpuCategory *spuCategory; // @dynamic spuCategory;
@property(nonatomic) unsigned long long spuId; // @dynamic spuId;
@property(retain, nonatomic) NSString *spuName; // @dynamic spuName;
@property(retain, nonatomic) EcWxaInfo *wxaInfo; // @dynamic wxaInfo;

@end

