//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"

@class NSString, StrongNotificationItemPB, WCFinderGlobalPushInfo;

@interface StrongNotificationItemAndMessagePB : MMObject <PBCoding>
{
    unsigned int uiStatue;
    unsigned int uiMesLocalID;
    NSString *nsForcePushId;
    NSString *nsUsrName;
    NSString *nsDescription;
    StrongNotificationItemPB *nsStrongNotificationItem;
    NSString *nsFeedID;
    NSString *nsSubject;
    double nsCreateTime;
    WCFinderGlobalPushInfo *nsFinderGlobalPushInfo;
}

+ (void)initialize;
+ (void)PBArrayAdd_nsFinderGlobalPushInfo;
+ (void)PBArrayAdd_nsCreateTime;
+ (void)PBArrayAdd_nsSubject;
+ (void)PBArrayAdd_uiMesLocalID;
+ (void)PBArrayAdd_nsFeedID;
+ (void)PBArrayAdd_nsStrongNotificationItem;
+ (void)PBArrayAdd_uiStatue;
+ (void)PBArrayAdd_nsDescription;
+ (void)PBArrayAdd_nsUsrName;
+ (void)PBArrayAdd_nsForcePushId;
- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderGlobalPushInfo *nsFinderGlobalPushInfo; // @synthesize nsFinderGlobalPushInfo;
@property(nonatomic) double nsCreateTime; // @synthesize nsCreateTime;
@property(retain, nonatomic) NSString *nsSubject; // @synthesize nsSubject;
@property(nonatomic) unsigned int uiMesLocalID; // @synthesize uiMesLocalID;
@property(retain, nonatomic) NSString *nsFeedID; // @synthesize nsFeedID;
@property(retain, nonatomic) StrongNotificationItemPB *nsStrongNotificationItem; // @synthesize nsStrongNotificationItem;
@property(nonatomic) unsigned int uiStatue; // @synthesize uiStatue;
@property(retain, nonatomic) NSString *nsDescription; // @synthesize nsDescription;
@property(retain, nonatomic) NSString *nsUsrName; // @synthesize nsUsrName;
@property(retain, nonatomic) NSString *nsForcePushId; // @synthesize nsForcePushId;
@property(readonly, copy) NSString *description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

