//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TAVMediaViewProtocol-Protocol.h"

@class AVPlayer, NSString;

@interface TAVMediaPlayerView : UIView <TAVMediaViewProtocol>
{
    _Bool _shouldAnimation;
    _Bool _paused;
    unsigned long long _fillMode;
    AVPlayer *_player;
}

+ (Class)layerClass;
- (void).cxx_destruct;
@property(nonatomic, getter=isPaused) _Bool paused; // @synthesize paused=_paused;
@property(nonatomic) _Bool shouldAnimation; // @synthesize shouldAnimation=_shouldAnimation;
@property(nonatomic) unsigned long long fillMode; // @synthesize fillMode=_fillMode;
- (void)refreshView;
@property(readonly, nonatomic) struct CGRect videoRect;
@property(nonatomic) __weak AVPlayer *player; // @synthesize player=_player;
- (void)updateLayerFillMode;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

