//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "TextStateDetailContentViewDelegate-Protocol.h"
#import "TextStateMgrExt-Protocol.h"

@class CContact, MMHeadImageView, NSString, TextStateDetailContentView, TextStateMediaContainerView, UIButton, UILabel;
@protocol TextStatePlanetFriendCellDelegate;

@interface TextStateSameTopicFriendCell : UICollectionViewCell <TextStateDetailContentViewDelegate, TextStateMgrExt>
{
    unsigned int _sessionScene;
    id <TextStatePlanetFriendCellDelegate> _delegate;
    CContact *_contact;
    long long _cellIndex;
    long long _fromScene;
    MMHeadImageView *_headImageView;
    UILabel *_nicknameLabel;
    UIButton *_profileButton;
    TextStateDetailContentView *_detailView;
    TextStateMediaContainerView *_bgMediaView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TextStateMediaContainerView *bgMediaView; // @synthesize bgMediaView=_bgMediaView;
@property(retain, nonatomic) TextStateDetailContentView *detailView; // @synthesize detailView=_detailView;
@property(retain, nonatomic) UIButton *profileButton; // @synthesize profileButton=_profileButton;
@property(retain, nonatomic) UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
@property(retain, nonatomic) MMHeadImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(nonatomic) long long fromScene; // @synthesize fromScene=_fromScene;
@property(nonatomic) unsigned int sessionScene; // @synthesize sessionScene=_sessionScene;
@property(nonatomic) long long cellIndex; // @synthesize cellIndex=_cellIndex;
@property(retain, nonatomic) CContact *contact; // @synthesize contact=_contact;
@property(nonatomic) __weak id <TextStatePlanetFriendCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)enterSelfLikeList:(id)arg1;
- (void)didSelectAtTextDetailView:(id)arg1;
- (void)onTextStateUpdateForUserName:(id)arg1;
- (void)didSelectSourceButton:(id)arg1;
- (void)onClickAtBackGround;
- (void)onClickAtHeadView:(id)arg1;
- (void)onClickAtHeadImage:(id)arg1;
- (void)layoutSubviews;
- (void)setupLayout;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)cellSizeToFitWidth:(double)arg1;
- (void)dealloc;
- (void)onFriendCellDisplay;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

