//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TextStateHistoryDaySorter : NSObject
{
    long long _day;
    long long _month;
    long long _year;
}

@property(nonatomic) long long year; // @synthesize year=_year;
@property(nonatomic) long long month; // @synthesize month=_month;
@property(nonatomic) long long day; // @synthesize day=_day;
- (_Bool)canAddHistoryInfo:(id)arg1;
- (id)initWithObj:(id)arg1;

@end

