//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TextState3rdPartyBaseHandler.h"

@class MMMusicVideoStatusOpenParams;

@interface TextState3rdPartyMusicPlayerHandler : TextState3rdPartyBaseHandler
{
    MMMusicVideoStatusOpenParams *_params;
}

+ (id)openParamsFormMusicBuffer:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) MMMusicVideoStatusOpenParams *params; // @synthesize params=_params;
- (id)reportActivityId;
- (id)getMusicInfo;
- (id)mediaDescription;
- (_Bool)allowReferBackground;
- (id)mediaCoverView;
- (id)mediaContentView;
- (_Bool)doHeadImageActionWithViewController:(id)arg1;
- (_Bool)doSourceActionWithViewController:(id)arg1;
- (id)convertSongInfoToMMMusicInfo:(id)arg1;
- (_Bool)useCoverForContent;
- (id)name;
- (id)customView;
- (_Bool)preferCustomView;
- (id)headImageView;
- (id)title;
- (unsigned int)type;
- (id)initWithBuffer:(id)arg1 keyBuffer:(id)arg2;
- (_Bool)supportCustomMedia;

@end

