//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface TextStatusHistory : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int createTime; // @dynamic createTime;
@property(retain, nonatomic) NSString *extInfo; // @dynamic extInfo;
@property(nonatomic) int likedCount; // @dynamic likedCount;
@property(nonatomic) int referencedCount; // @dynamic referencedCount;
@property(retain, nonatomic) NSString *textStatusId; // @dynamic textStatusId;
@property(retain, nonatomic) NSString *topicId; // @dynamic topicId;

@end

