//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TPAssetResourceLoader, TPAssetResourceLoadingRequest;

@protocol TPAssetResourceLoaderDelegate <NSObject>
- (void)tpResourceLoader:(TPAssetResourceLoader *)arg1 didCancelLoadingRequest:(TPAssetResourceLoadingRequest *)arg2;
- (_Bool)tpResourceLoader:(TPAssetResourceLoader *)arg1 shouldWaitForLoadingOfRequestedResource:(TPAssetResourceLoadingRequest *)arg2;
@end

