//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TRTCCdnPlayerConfig, TRTCDecoderFactory, TXLivePlayer;

@interface TRTCCdnPlayerManager : NSObject
{
    TXLivePlayer *_player;
    TRTCCdnPlayerConfig *_config;
    TRTCDecoderFactory *_mWXVideoDecoder;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TRTCDecoderFactory *mWXVideoDecoder; // @synthesize mWXVideoDecoder=_mWXVideoDecoder;
@property(retain, nonatomic) TRTCCdnPlayerConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) TXLivePlayer *player; // @synthesize player=_player;
- (void)updatePlayerCache;
- (void)setEnableHEVAndAVCDecoder:(_Bool)arg1;
- (void)setCloseHWDecoder;
- (void)setEnableMessage:(_Bool)arg1;
- (void)setConnectRetryInterval:(int)arg1;
- (void)setConnectRetryCount:(int)arg1;
- (void)setDefaultPlayerConfig;
- (void)setCacheType:(unsigned long long)arg1 minCache:(int)arg2 maxCache:(int)arg3;
- (void)setRenderMode:(long long)arg1;
- (void)setOrientation:(long long)arg1;
- (void)setDebugLogEnabled:(_Bool)arg1;
- (void)setMute:(_Bool)arg1;
- (_Bool)isPlaying;
- (void)resume;
- (void)pause;
- (void)stopPlay;
- (int)switchStream:(id)arg1;
- (void)startPlay:(id)arg1;
- (void)applyConfigToPlayer;
- (void)dealloc;
- (id)initWithContainerView:(id)arg1 delegate:(id)arg2;

@end

