//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, UIImage;

@protocol V2TXLivePusherJSAdapterDelegate <NSObject>

@optional
- (void)onSnapshotComplete:(UIImage *)arg1;
- (void)onBGMComplete:(long long)arg1;
- (void)onBGMProgress:(long long)arg1 durationMs:(long long)arg2;
- (void)onBGMStart:(long long)arg1;
- (void)onAudioVolumeEvaluation:(long long)arg1;
- (void)onNetStatus:(NSDictionary *)arg1;
- (void)onPushEvent:(long long)arg1 withParam:(NSDictionary *)arg2;
@end

