//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface ValFeature : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int autoPlay; // @dynamic autoPlay;
@property(nonatomic) unsigned long long endPlayTime; // @dynamic endPlayTime;
@property(nonatomic) unsigned long long exposeTimeMs; // @dynamic exposeTimeMs;
@property(nonatomic) unsigned long long lastPlayTime; // @dynamic lastPlayTime;
@property(nonatomic) unsigned long long startPlayTime; // @dynamic startPlayTime;
@property(nonatomic) unsigned int stayTime; // @dynamic stayTime;
@property(nonatomic) unsigned long long stayTimeMs; // @dynamic stayTimeMs;
@property(nonatomic) unsigned long long stopTimes; // @dynamic stopTimes;
@property(nonatomic) unsigned int vidPlayLen; // @dynamic vidPlayLen;
@property(nonatomic) unsigned long long vidPlayTimeMs; // @dynamic vidPlayTimeMs;
@property(nonatomic) unsigned long long vidPlayingTimeMs; // @dynamic vidPlayingTimeMs;

@end

