//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseResponse, NSString, VerifyUserSpamInfo;

@interface VerifyUserResponse : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) NSString *ctx; // @dynamic ctx;
@property(retain, nonatomic) NSString *encryptUserName; // @dynamic encryptUserName;
@property(retain, nonatomic) NSString *userName; // @dynamic userName;
@property(retain, nonatomic) VerifyUserSpamInfo *verifyUserSpamInfo; // @dynamic verifyUserSpamInfo;

@end

