//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WAAuthorizeResultInfo : NSObject
{
    unsigned int _avatarId;
    unsigned int _avatarOpt;
    unsigned long long _scopeId;
    NSString *_sessionId;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int avatarOpt; // @synthesize avatarOpt=_avatarOpt;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) unsigned long long scopeId; // @synthesize scopeId=_scopeId;
@property(nonatomic) unsigned int avatarId; // @synthesize avatarId=_avatarId;
- (id)init;

@end

