//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IWABusinessService-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class NSMutableArray, NSString;

@interface WABusinessProxy : NSObject <PBMessageObserverDelegate, IWABusinessService>
{
    NSMutableArray *_uploadingInfos;
}

+ (void)updateAppServiceConfigRes;
+ (void)onMPShortLinkGlobalHightLightSwitchDidChanged;
+ (void)showPayFunctionXAgreementWarningTip;
+ (_Bool)checkPayFunctionBanByXAgreement;
+ (id)getLoginUsrInfo;
+ (_Bool)isLogin;
+ (id)genAppAuthSettingWithWeAppContact:(id)arg1;
+ (id)genProfileWithParameter:(id)arg1;
+ (id)getMMHeadImageViewWithUsername:(id)arg1 imageSize:(struct CGSize)arg2;
+ (void)didUserSelectCopyMPShortLinkSuccess:(id)arg1 inWebViewController:(id)arg2 processCompletion:(CDUnknownBlockType)arg3;
+ (void)clearExposeSnapShot:(id)arg1;
+ (id)saveExposeSnapShot:(id)arg1;
+ (id)genWebViewController:(id)arg1;
+ (void)onWeAppDidPresentWithPresentingViewController:(id)arg1;
+ (void)onWeAppNavigateToMiniProgramCancelledFromAppId:(id)arg1 toAppId:(id)arg2;
+ (void)onWeAppNavigateToMiniProgramFailFromAppId:(id)arg1 toAppId:(id)arg2;
+ (void)onWeAppNavigateToMiniProgramSuccessFromAppId:(id)arg1 toAppId:(id)arg2;
+ (void)onWeAppNavigateToMiniProgramFromAppId:(id)arg1 toAppId:(id)arg2 pagePath:(id)arg3 fromScene:(unsigned long long)arg4 fromSceneNote:(id)arg5 adInfo:(id)arg6;
+ (void)showUserGuide;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *uploadingInfos; // @synthesize uploadingInfos=_uploadingInfos;
- (void)OnCdnUpload:(id)arg1;
- (void)uploadMPShortLink:(id)arg1 snapShotForWebVC:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

