//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class MMUIButton, UIImageView, UILongPressGestureRecognizer;
@protocol WACapsuleViewDelegate;

@interface WACapsuleView : MMUIView
{
    MMUIView *_menuView;
    MMUIButton *_menuMoreButton;
    MMUIButton *_menuExitButton;
    MMUIButton *_menuStateButton;
    UIImageView *_menuIconView;
    UILongPressGestureRecognizer *_longPressRecognizer;
    UILongPressGestureRecognizer *_moreLongPressRecognizer;
    _Bool _isTrigerMoreLongPress;
    double _lastSystemNavigationBarHeight;
    _Bool _needAdaptIpad;
    id <WACapsuleViewDelegate> _delegate;
    long long _navMode;
    long long _menuState;
}

+ (struct CGSize)menuSize;
+ (_Bool)shouldUseSmallMenu;
- (void).cxx_destruct;
@property(nonatomic) _Bool needAdaptIpad; // @synthesize needAdaptIpad=_needAdaptIpad;
@property(nonatomic) long long menuState; // @synthesize menuState=_menuState;
@property(nonatomic) long long navMode; // @synthesize navMode=_navMode;
@property(nonatomic) __weak id <WACapsuleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onLongPressMoreItem:(id)arg1;
- (void)onLongPressExitItem:(id)arg1;
- (id)getMenuExitButton;
- (id)getMenuMoreButton;
- (id)genStateButton;
- (id)genMenuView;
- (void)onExit;
- (void)onMore;
- (id)getIconNameForCurrentNavMode:(id)arg1 HighLight:(_Bool)arg2;
- (id)getIconNameForCurrentNavMode:(id)arg1;
- (id)stateBackgroundIconName;
- (id)voiceRecordStateIconName;
- (id)POIBackgroundStateIconName;
- (id)POIStateIconName;
- (id)videoRecordStateIconName;
- (id)exitButtonIconName;
- (id)moreButtonIconName;
- (void)changeMenuStateWithIcon:(id)arg1 AccessbilityLabel:(id)arg2;
- (void)changeMenuStateToRecordingVideo;
- (void)changeMenuStateToRecordingVoice;
- (void)changeMenuStateToBackgroundLocation;
- (void)changeMenuStateToLocation;
- (void)changeMenuStateToNormal;
- (void)resetMenuViewIcon;
- (void)onWebViewDidAppear;
- (void)setExpendTouchInsets:(struct UIEdgeInsets)arg1;
- (void)fsmenu_updateContent;
- (void)resetMenuState;
- (id)webview;
- (void)onApplicationWillEnterForeground:(id)arg1;
- (void)layoutSubviews;
- (void)updateMenuViewWitNavMode:(long long)arg1;
- (void)setHidden:(_Bool)arg1;
- (void)dealloc;
- (id)initWithNavMode:(long long)arg1;

@end

