//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableDictionary, NSString;

@interface WACanvasFrameSetView : UIView
{
    _Bool _hasSetup;
    NSString *_rootId;
    NSString *_name;
    NSString *_appId;
    NSString *_identifier;
    NSMutableDictionary *_dicCanvasFrameView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hasSetup; // @synthesize hasSetup=_hasSetup;
@property(retain, nonatomic) NSMutableDictionary *dicCanvasFrameView; // @synthesize dicCanvasFrameView=_dicCanvasFrameView;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *rootId; // @synthesize rootId=_rootId;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)stopAllCanvasFrame;
- (_Bool)addCanvasFrameViewWithJSContext:(id)arg1 canvasId:(id)arg2;
- (id)randomCanvasFrameViewIfHas;
- (id)canvasFrameViewForId:(id)arg1;
- (_Bool)existCanvasFrameViewForId:(id)arg1;
- (_Bool)existCanvasFrameView;
- (void)setupAfterAvailable;
- (void)setHidden:(_Bool)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)description;
- (void)dealloc;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1 rootId:(id)arg2 name:(id)arg3 appId:(id)arg4;
- (id)initWithRootId:(id)arg1 name:(id)arg2 appId:(id)arg3;

@end

