//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

@class NSMutableArray;

@interface WAJSEventHandler_addMapMarkers : WAJSEventHandler_BaseEvent
{
    NSMutableArray *_markersAddMap;
    NSMutableArray *_markersAddCluster;
}

+ (id)makeIconImage:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *markersAddCluster; // @synthesize markersAddCluster=_markersAddCluster;
@property(retain, nonatomic) NSMutableArray *markersAddMap; // @synthesize markersAddMap=_markersAddMap;
- (void)addMapMarker:(id)arg1 marker:(id)arg2;
- (void)handleJSEvent:(id)arg1;

@end

