//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

@class NSMutableDictionary;

@interface WAJSEventHandler_stat : WAJSEventHandler_BaseEvent
{
    NSMutableDictionary *_recursiveDic;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *recursiveDic; // @synthesize recursiveDic=_recursiveDic;
- (void)traversePath:(id)arg1 isLocalCache:(_Bool)arg2;
- (id)dicFromStat:(struct stat)arg1;
- (void)innerHandleJSEven:(id)arg1;
- (void)handleJSEvent:(id)arg1;

@end

