//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UIColor, UIImage, UIImageView, UILabel;
@protocol WANavAlertTitleViewDelegate;

@interface WANavAlertTitleView : UIView
{
    id <WANavAlertTitleViewDelegate> _delegate;
    UIImageView *_alertIconView;
    UILabel *_alertLabel;
    UIButton *_entryBtn;
    NSString *_waName;
    UIColor *_normalColor;
    UIColor *_highlightColor;
    UIImage *_normalIcon;
    UIImage *_highlightIcon;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *highlightIcon; // @synthesize highlightIcon=_highlightIcon;
@property(retain, nonatomic) UIImage *normalIcon; // @synthesize normalIcon=_normalIcon;
@property(retain, nonatomic) UIColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property(retain, nonatomic) UIColor *normalColor; // @synthesize normalColor=_normalColor;
@property(retain, nonatomic) NSString *waName; // @synthesize waName=_waName;
@property(retain, nonatomic) UIButton *entryBtn; // @synthesize entryBtn=_entryBtn;
@property(retain, nonatomic) UILabel *alertLabel; // @synthesize alertLabel=_alertLabel;
@property(retain, nonatomic) UIImageView *alertIconView; // @synthesize alertIconView=_alertIconView;
@property(nonatomic) __weak id <WANavAlertTitleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onEntryBtnClicked:(id)arg1;
- (void)endHighlight;
- (void)beginHighlight;
- (void)alert;
- (_Bool)shouldShowEntry;
- (void)updateEntryBtnWithWeAppName:(id)arg1;
- (void)layoutSubviews;
- (void)initSubviews;
- (id)init;

@end

