//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZZFLEXTableViewController.h"

@class NSMutableArray, NSString;

@interface WARelatedAppViewController : ZZFLEXTableViewController
{
    NSString *_teamName;
    NSMutableArray *_relateWeappList;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *relateWeappList; // @synthesize relateWeappList=_relateWeappList;
@property(retain, nonatomic) NSString *teamName; // @synthesize teamName=_teamName;
- (void)reloadListUI;
- (void)dealloc;
- (void)onBackButtonClicked:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithTeamName:(id)arg1 relatedAppList:(id)arg2;

@end

