//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUINavigationController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"
#import "WAPopInteractiveTransitionDelegate-Protocol.h"

@class FixDocumentPresent, MMUINavigationBar, NSMutableArray, NSString, UIView, UIViewController, WAMenuPopInteractiveTransition;
@protocol WAUINavigationControllerDelegate;

@interface WAUINavigationController : MMUINavigationController <UIViewControllerTransitioningDelegate, UIGestureRecognizerDelegate, WAPopInteractiveTransitionDelegate>
{
    _Bool _isInSheetMode;
    _Bool _hasLoadResizable;
    _Bool _hasAdjustSize;
    _Bool _isPortrait;
    _Bool _isResizable;
    _Bool _isAuto;
    _Bool _isGame;
    _Bool _isEnableDark;
    id <WAUINavigationControllerDelegate> _naviDelegate;
    UIViewController *_viewControllerBeingPushedOrPopTo;
    WAMenuPopInteractiveTransition *_dismissInteractiveTransition;
    MMUINavigationBar *_customNavigationBar;
    FixDocumentPresent *_presentProxy;
    UIView *_bottomView;
    long long _viewState;
    NSMutableArray *_arrAppearAction;
}

+ (_Bool)shouldUseCustomeNavigationBar;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *arrAppearAction; // @synthesize arrAppearAction=_arrAppearAction;
@property(nonatomic) long long viewState; // @synthesize viewState=_viewState;
@property(nonatomic) _Bool isEnableDark; // @synthesize isEnableDark=_isEnableDark;
@property(nonatomic) _Bool isGame; // @synthesize isGame=_isGame;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) _Bool isAuto; // @synthesize isAuto=_isAuto;
@property(nonatomic) _Bool isResizable; // @synthesize isResizable=_isResizable;
@property(nonatomic) _Bool isPortrait; // @synthesize isPortrait=_isPortrait;
@property(nonatomic) _Bool hasAdjustSize; // @synthesize hasAdjustSize=_hasAdjustSize;
@property(nonatomic) _Bool hasLoadResizable; // @synthesize hasLoadResizable=_hasLoadResizable;
@property(retain, nonatomic) FixDocumentPresent *presentProxy; // @synthesize presentProxy=_presentProxy;
@property(retain, nonatomic) MMUINavigationBar *customNavigationBar; // @synthesize customNavigationBar=_customNavigationBar;
@property(retain, nonatomic) WAMenuPopInteractiveTransition *dismissInteractiveTransition; // @synthesize dismissInteractiveTransition=_dismissInteractiveTransition;
@property(nonatomic) _Bool isInSheetMode; // @synthesize isInSheetMode=_isInSheetMode;
@property(retain, nonatomic) UIViewController *viewControllerBeingPushedOrPopTo; // @synthesize viewControllerBeingPushedOrPopTo=_viewControllerBeingPushedOrPopTo;
@property(nonatomic) __weak id <WAUINavigationControllerDelegate> naviDelegate; // @synthesize naviDelegate=_naviDelegate;
- (long long)overrideUserInterfaceStyle;
- (_Bool)shouldUsePresentWhenPushViewController:(id)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) double bottomViewWidth;
@property(readonly, nonatomic) double bottomViewHeight;
- (void)layoutCenterLoading;
- (void)addBottomView;
- (void)scaleViewIfUnresizable;
- (void)adjustViewSizeIfUnresizable;
- (void)viewDidLoad;
@property(readonly, nonatomic) _Bool isCurrentPagePortraitForIpad;
@property(readonly, nonatomic) _Bool hasScaleToAdaptIpad;
- (void)viewWillLayoutSubviews;
- (void)doAppearAction;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)addAppearAction:(CDUnknownBlockType)arg1;
- (void)viewDidPresent:(_Bool)arg1;
- (void)tryForceRotationWhenPushOrPop:(id)arg1 ToViewController:(id)arg2;
- (id)popToRootViewControllerAnimated:(_Bool)arg1;
- (id)popToViewController:(id)arg1 animated:(_Bool)arg2;
- (id)popViewControllerAnimated:(_Bool)arg1;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)dismissPresentedViewController;
- (void)PresentModalViewControllerInPushAnimation:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)PushViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)PushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;
- (id)initWithRootViewController:(id)arg1;
- (void)onPopBackInteractiveTransitionBegin:(id)arg1;
- (id)interactionControllerForDismissal:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)setupAnimationTransitionOfVC:(id)arg1 navVC:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

