//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCAccountBaseControlLogic.h"

#import "MMWebViewDelegate-Protocol.h"
#import "WCAccountAffiliatedAcctDelegate-Protocol.h"
#import "WCPrivacyPolicyControlLogicDelegate-Protocol.h"

@class NSString, WCPrivacyPolicyControlLogic;

@interface WCAccountAffiliatedAcctRegControlLogic : WCAccountBaseControlLogic <WCAccountAffiliatedAcctDelegate, WCPrivacyPolicyControlLogicDelegate, MMWebViewDelegate>
{
    CDUnknownBlockType _onRegSuccessBlock;
    WCPrivacyPolicyControlLogic *_privacyPolicyLogic;
    NSString *_clientSessionId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *clientSessionId; // @synthesize clientSessionId=_clientSessionId;
@property(retain, nonatomic) WCPrivacyPolicyControlLogic *privacyPolicyLogic; // @synthesize privacyPolicyLogic=_privacyPolicyLogic;
@property(copy, nonatomic) CDUnknownBlockType onRegSuccessBlock; // @synthesize onRegSuccessBlock=_onRegSuccessBlock;
- (void)webViewDidReturn:(id)arg1;
- (void)onWebViewCloseAndGoNext:(id)arg1 webVC:(id)arg2 customClose:(_Bool *)arg3;
- (void)onWCPrivacyPolicyControlLogicClickDiagree;
- (void)onWCPrivacyPolicyControlLogicClickAgree;
- (void)onLeaveViewController:(id)arg1;
- (void)onShowHelpPage;
- (void)end;
- (void)nextToRegister;
- (void)nextToSetPassword;
- (void)nextToH5;
- (void)nextToRegUseNewPhone;
- (void)reportWithPage:(unsigned int)arg1 action:(unsigned int)arg2 module:(unsigned int)arg3;
- (_Bool)uploadHeadImgIfNeeded;
- (void)regAffiliatedAcctWithHeadImageTaskInfo:(id)arg1 headImgData:(id)arg2;
- (void)showPrivacyPolicy;
- (void)precheckAffiliatedAcct;
- (void)openWebViewWithUrl:(id)arg1;
- (void)startLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

