//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class MMUILabel, WCAdRollTextView, WCDataItem, WCFinderLiveIconImageView;

@interface WCAdLiveDisplayView : MMUIView
{
    _Bool _isFullCard;
    WCDataItem *_dataItem;
    MMUIView *_liveStatusView;
    WCFinderLiveIconImageView *_liveStatusIcon;
    MMUILabel *_liveStatusText;
    MMUIView *_liveDescView;
    WCAdRollTextView *_liveDescText;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCAdRollTextView *liveDescText; // @synthesize liveDescText=_liveDescText;
@property(retain, nonatomic) MMUIView *liveDescView; // @synthesize liveDescView=_liveDescView;
@property(retain, nonatomic) MMUILabel *liveStatusText; // @synthesize liveStatusText=_liveStatusText;
@property(retain, nonatomic) WCFinderLiveIconImageView *liveStatusIcon; // @synthesize liveStatusIcon=_liveStatusIcon;
@property(retain, nonatomic) MMUIView *liveStatusView; // @synthesize liveStatusView=_liveStatusView;
@property(nonatomic) _Bool isFullCard; // @synthesize isFullCard=_isFullCard;
@property(retain, nonatomic) WCDataItem *dataItem; // @synthesize dataItem=_dataItem;
- (void)onViewDisplay:(_Bool)arg1;
- (void)updateLiveStatus:(int)arg1;
- (void)initView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 dataItem:(id)arg2 isFullCard:(_Bool)arg3;

@end

