//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCAdvertiseOperationLogicBase.h"

#import "WCAdCouponHalfScreenViewDelegate-Protocol.h"
#import "WCCanvasDynamicDataLoaderDelegate-Protocol.h"

@class NSString, WCAdCouponHalfScreenView, WCAdCouponInfo, WCAdvertiseInfo, WCCanvasDynamicDataLoader;
@protocol WCAdCouponLogicDelegate;

@interface WCAdCouponLogic : WCAdvertiseOperationLogicBase <WCAdCouponHalfScreenViewDelegate, WCCanvasDynamicDataLoaderDelegate>
{
    id <WCAdCouponLogicDelegate> _delegate;
    WCAdCouponInfo *_adCouponInfo;
    WCAdCouponHalfScreenView *_halfScreenView;
    WCCanvasDynamicDataLoader *_dataLoader;
    WCAdvertiseInfo *_adData;
    NSString *_snsId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *snsId; // @synthesize snsId=_snsId;
@property(retain, nonatomic) WCAdvertiseInfo *adData; // @synthesize adData=_adData;
@property(retain, nonatomic) WCCanvasDynamicDataLoader *dataLoader; // @synthesize dataLoader=_dataLoader;
@property(retain, nonatomic) WCAdCouponHalfScreenView *halfScreenView; // @synthesize halfScreenView=_halfScreenView;
@property(retain, nonatomic) WCAdCouponInfo *adCouponInfo; // @synthesize adCouponInfo=_adCouponInfo;
@property(nonatomic) __weak id <WCAdCouponLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onGetCouponWithResult:(long long)arg1 errMsg:(id)arg2;
- (id)fetchMMViewController;
- (void)hideLoadingView;
- (void)showLoadingView;
- (void)onConfirmButtonClickWithCouponAppId:(id)arg1 andStockId:(id)arg2;
- (void)start;
- (id)initWithCouponInfo:(id)arg1 adAdData:(id)arg2 andSnsId:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

