//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WCAdInteractionDeterminationInfo, WCAdInteractionResourceInfo;

@protocol WCAdInteractionContentViewDelegate <NSObject>
- (void)deviceMotionAccelerationChangedWithX:(double)arg1 y:(double)arg2 z:(double)arg3;
- (void)deviceMotionOrientationChangedWithXAngle:(double)arg1 yAngle:(double)arg2 zAngle:(double)arg3;
- (void)contentViewBeClickedWithResourceId:(NSString *)arg1;
- (WCAdInteractionDeterminationInfo *)fetchDeterminationInfoWithResourceId:(NSString *)arg1;
- (WCAdInteractionResourceInfo *)fetchResourceInfoWithResourceId:(NSString *)arg1;
@end

