//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ILinkEventExt-Protocol.h"

@class NSMutableArray, NSString, RichTextView, UIColor, UIFont, UIImageView, UITapGestureRecognizer;

@interface WCAgreementCheckBox : UIView <ILinkEventExt>
{
    _Bool _selected;
    _Bool _autoExpandHitArea;
    _Bool _needsUpdateAccessibility;
    CDUnknownBlockType _selectBlock;
    CDUnknownBlockType _tapLinkBlock;
    NSString *_agreement;
    UIColor *_textColor;
    UIFont *_font;
    UIImageView *_iconView;
    RichTextView *_richTextView;
    UITapGestureRecognizer *_tapGesture;
    UIColor *_selectedIconColor;
    UIColor *_unselectedIconColor;
    NSMutableArray *_accessibilityElements;
    struct UIEdgeInsets _expandHitAreaInsets;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool needsUpdateAccessibility; // @synthesize needsUpdateAccessibility=_needsUpdateAccessibility;
@property(retain, nonatomic) NSMutableArray *accessibilityElements; // @synthesize accessibilityElements=_accessibilityElements;
@property(nonatomic) struct UIEdgeInsets expandHitAreaInsets; // @synthesize expandHitAreaInsets=_expandHitAreaInsets;
@property(retain, nonatomic) UIColor *unselectedIconColor; // @synthesize unselectedIconColor=_unselectedIconColor;
@property(retain, nonatomic) UIColor *selectedIconColor; // @synthesize selectedIconColor=_selectedIconColor;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) RichTextView *richTextView; // @synthesize richTextView=_richTextView;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) _Bool autoExpandHitArea; // @synthesize autoExpandHitArea=_autoExpandHitArea;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) NSString *agreement; // @synthesize agreement=_agreement;
@property(copy, nonatomic) CDUnknownBlockType tapLinkBlock; // @synthesize tapLinkBlock=_tapLinkBlock;
@property(copy, nonatomic) CDUnknownBlockType selectBlock; // @synthesize selectBlock=_selectBlock;
@property(nonatomic, getter=isSelected) _Bool selected; // @synthesize selected=_selected;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onTextClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onTapCheckBox:(id)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (long long)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (void)updateAccessibilityIfNeeded;
- (void)adjustExpandHitAreaInsetsIfNeeded;
- (void)shake;
- (void)doSelect;
- (void)setFrame:(struct CGRect)arg1;
- (id)iconColorForSelected:(_Bool)arg1;
- (void)setIconColor:(id)arg1 forSelected:(_Bool)arg2;
- (void)callSelectBlockIfNeeded;
- (double)richTextViewMaxWidthFromWidth:(double)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)initGestures;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

