//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface WCCanvasRandomLayoutTransitionImgInfo : MMObject <NSCoding>
{
    NSString *_transitionImgUrl;
    NSString *_transitionColor;
    double _transitionColorAlpha;
}

- (void).cxx_destruct;
@property(nonatomic) double transitionColorAlpha; // @synthesize transitionColorAlpha=_transitionColorAlpha;
@property(retain, nonatomic) NSString *transitionColor; // @synthesize transitionColor=_transitionColor;
@property(retain, nonatomic) NSString *transitionImgUrl; // @synthesize transitionImgUrl=_transitionImgUrl;
- (_Bool)isValid;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

