//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCCanvasFrameLayout.h"

@class WCCanvasComponent, WCCanvasComponentItem;

@interface WCCanvasRandomLayout : WCCanvasFrameLayout
{
    WCCanvasComponentItem *_theChosenItem;
    WCCanvasComponent *_theChosenComponent;
}

+ (struct CGSize)calcSizeForCanvasItem:(id)arg1 dataItem:(id)arg2 orientation:(long long)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) WCCanvasComponent *theChosenComponent; // @synthesize theChosenComponent=_theChosenComponent;
@property(retain, nonatomic) WCCanvasComponentItem *theChosenItem; // @synthesize theChosenItem=_theChosenItem;
- (id)fetchDestComponentForSpecialAnim;
- (void)resetSightViewAudioState:(_Bool)arg1;
- (void)componentWillStopState:(_Bool)arg1;
- (void)componentWillResumeState:(_Bool)arg1;
- (void)componentDidFullyAppearInMainScreen:(_Bool)arg1;
- (void)componentWillEnterForeground;
- (void)componentDidEnterBackground;
- (void)componentAppearFactorChagneInMainScreen;
- (void)componentWillDisappearInMainScreen:(_Bool)arg1;
- (void)componentWillAppearInMainScreen:(_Bool)arg1;
- (void)configureWithCanvasItem:(id)arg1 dataItem:(id)arg2 orientation:(long long)arg3;
- (void)layoutSubviews;

@end

