//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class WecoinNewUserTips;

@interface WCCoinNewUserTipsDetailView : UIView
{
    WecoinNewUserTips *_tips;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WecoinNewUserTips *tips; // @synthesize tips=_tips;
- (void)done;
- (void)layoutSubviews;
- (void)layout;
- (id)initWithData:(id)arg1;

@end

