//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSDate, NSString;

@interface WCDBBackupRecord : NSObject <PBCoding>
{
    long long bakeupSize;
    long long backupTimes;
    NSDate *startRecordTime;
}

+ (void)initialize;
+ (void)PBArrayAdd_startRecordTime;
+ (void)PBArrayAdd_backupTimes;
+ (void)PBArrayAdd_bakeupSize;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *startRecordTime; // @synthesize startRecordTime;
@property(nonatomic) long long backupTimes; // @synthesize backupTimes;
@property(nonatomic) long long bakeupSize; // @synthesize bakeupSize;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

