//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableArray, NSString;
@protocol WCFinderAddPOIViewModelDelegate;

@interface WCFinderAddPOIViewModel : NSObject
{
    _Bool _continueFlag;
    id <WCFinderAddPOIViewModelDelegate> _delegate;
    NSMutableArray *_poiInfoList;
    NSString *_finderUsername;
    NSData *_lastBuffer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSData *lastBuffer; // @synthesize lastBuffer=_lastBuffer;
@property(retain, nonatomic) NSString *finderUsername; // @synthesize finderUsername=_finderUsername;
@property(nonatomic) _Bool continueFlag; // @synthesize continueFlag=_continueFlag;
@property(retain, nonatomic) NSMutableArray *poiInfoList; // @synthesize poiInfoList=_poiInfoList;
@property(nonatomic) __weak id <WCFinderAddPOIViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)bindPOIWithIds:(id)arg1;
- (void)fetchDataWithLastBuffer:(id)arg1;
- (void)fetchNextPageData;
- (void)fetchFirstPageData;
- (id)initWithFinderUsername:(id)arg1;

@end

