//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSIndexPath, NSString, WCFinderFeedContentVM, WCFinderSnSLiveSectionTableViewCell;

@protocol WCFinderSnSLiveSectionTableViewCellDelegate <NSObject>

@optional
- (void)onSnsLiveSectionClickClearBtnAction;
- (void)onClearAllSnSLiveSectionData;
- (NSString *)finderLiveSectionTableViewCell:(WCFinderSnSLiveSectionTableViewCell *)arg1 customTitleWithContentVM:(WCFinderFeedContentVM *)arg2;
- (void)finderLiveSectionTableViewCell:(WCFinderSnSLiveSectionTableViewCell *)arg1 endExposeLiveContentVM:(WCFinderFeedContentVM *)arg2;
- (void)finderLiveSectionTableViewCell:(WCFinderSnSLiveSectionTableViewCell *)arg1 didExposeLiveContentVM:(WCFinderFeedContentVM *)arg2;
- (void)finderLiveSectionTableViewCellFetchMoreLiveList:(WCFinderSnSLiveSectionTableViewCell *)arg1;
- (void)onViewMoreLiveList;
- (void)onDidExposeLiveAtIndex:(NSIndexPath *)arg1 inLives:(NSArray *)arg2;
- (void)onDidSelectLiveAtIndex:(NSIndexPath *)arg1 inLives:(NSArray *)arg2;
@end

