//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSArray, NSString;

@interface WCFinderGetLiveTabsInfo : NSObject <PBCoding>
{
    NSString *title;
    unsigned long long hideTabs;
    unsigned long long prefechTabPullType;
    unsigned long long prefechPreTabPullType;
    unsigned long long prefechNextTabPullType;
    NSArray *liveTabList;
}

+ (id)finderGetLiveTabsInfoFrom:(id)arg1;
+ (void)initialize;
+ (void)PBArrayAdd_liveTabList;
+ (void)PBArrayAdd_prefechNextTabPullType;
+ (void)PBArrayAdd_prefechPreTabPullType;
+ (void)PBArrayAdd_prefechTabPullType;
+ (void)PBArrayAdd_hideTabs;
+ (void)PBArrayAdd_title;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *liveTabList; // @synthesize liveTabList;
@property(nonatomic) unsigned long long prefechNextTabPullType; // @synthesize prefechNextTabPullType;
@property(nonatomic) unsigned long long prefechPreTabPullType; // @synthesize prefechPreTabPullType;
@property(nonatomic) unsigned long long prefechTabPullType; // @synthesize prefechTabPullType;
@property(nonatomic) unsigned long long hideTabs; // @synthesize hideTabs;
@property(retain, nonatomic) NSString *title; // @synthesize title;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

