//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface WCFinderIntentItem : NSObject
{
    NSMutableDictionary *_map;
    NSString *_currIntentHash;
    NSString *_prevIntentHash;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *prevIntentHash; // @synthesize prevIntentHash=_prevIntentHash;
@property(retain, nonatomic) NSString *currIntentHash; // @synthesize currIntentHash=_currIntentHash;
@property(retain, nonatomic) NSMutableDictionary *map; // @synthesize map=_map;
- (id)info;
- (id)init;

@end

