//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCFinderDataItemExt-Protocol.h"
#import "WCFinderMegaVideoDataExt-Protocol.h"

@class NSData, NSMutableArray, NSString, WCFinderMegalikeViewModel;
@protocol WCFinderLikeListFlowViewModelDelegate;

@interface WCFinderLikeListFlowViewModel : NSObject <WCFinderDataItemExt, WCFinderMegaVideoDataExt>
{
    _Bool _continueFlag;
    id <WCFinderLikeListFlowViewModelDelegate> _delegate;
    unsigned long long _refreshTime;
    unsigned long long _finderTotalCount;
    unsigned long long _megavideoTotalCount;
    NSMutableArray *_contentVMArray;
    WCFinderMegalikeViewModel *_megaVideoViewModel;
    unsigned long long _state;
    NSData *_lastBuf;
    unsigned long long _totalCount;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool continueFlag; // @synthesize continueFlag=_continueFlag;
@property(nonatomic) unsigned long long totalCount; // @synthesize totalCount=_totalCount;
@property(retain, nonatomic) NSData *lastBuf; // @synthesize lastBuf=_lastBuf;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) WCFinderMegalikeViewModel *megaVideoViewModel; // @synthesize megaVideoViewModel=_megaVideoViewModel;
@property(retain, nonatomic) NSMutableArray *contentVMArray; // @synthesize contentVMArray=_contentVMArray;
@property(nonatomic) unsigned long long megavideoTotalCount; // @synthesize megavideoTotalCount=_megavideoTotalCount;
@property(nonatomic) unsigned long long finderTotalCount; // @synthesize finderTotalCount=_finderTotalCount;
@property(nonatomic) unsigned long long refreshTime; // @synthesize refreshTime=_refreshTime;
@property(nonatomic) __weak id <WCFinderLikeListFlowViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onFinderMegaVideoDelete:(id)arg1;
- (void)onFinderMegaVideoLikeStatusChangedRet:(_Bool)arg1 videoId:(id)arg2 isLike:(_Bool)arg3;
- (void)onFinderDataItemIsLikedUpdateByExtention:(id)arg1;
- (id)generateLikeListViewModel;
- (void)getLocalFirstPageData;
- (void)fetchNextPageData;
- (void)fetchFirstPageData;
- (void)fetchServerDataWithLastBuffer:(id)arg1;
- (_Bool)hasMoreData;
- (id)contentVMAtIndex:(unsigned long long)arg1;
- (unsigned long long)dataCount;
- (unsigned long long)likeTotalCount;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

