//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, WCTDatabase, WCTTable;

@interface WCFinderMsgSessionStatusStorage : NSObject
{
    WCTDatabase *_sessionStatusDB;
    WCTTable *_sessionStatusTable;
    NSMutableDictionary *_sessionStatusDic;
    CDUnknownBlockType _recoverBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType recoverBlock; // @synthesize recoverBlock=_recoverBlock;
@property(retain, nonatomic) NSMutableDictionary *sessionStatusDic; // @synthesize sessionStatusDic=_sessionStatusDic;
@property(retain, nonatomic) WCTTable *sessionStatusTable; // @synthesize sessionStatusTable=_sessionStatusTable;
@property(retain, nonatomic) WCTDatabase *sessionStatusDB; // @synthesize sessionStatusDB=_sessionStatusDB;
- (void)didRecoverDatabase;
- (void)willRecoverDatabase;
- (void)setDBIsNeedRecover:(_Bool)arg1;
- (_Bool)isDBNeedRecover;
- (void)removeAllSesstionStatusWithAccountType:(unsigned int)arg1;
- (id)sessionStatusListWithMyAccountType:(unsigned int)arg1 isInNormalSession:(_Bool)arg2;
- (id)sessionStatusWithSessionId:(id)arg1;
- (void)addOrUpdateSessionStatus:(id)arg1;
- (unsigned long long)sessionStatusListCount;
- (void)clearSessionStatusCache;
- (void)loadDB;
- (void)addDBRecoverObserver;
- (void)initDBAndSetRecoverBlock:(CDUnknownBlockType)arg1;
- (id)init;
- (void)dealloc;

@end

