//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol WCFinderPlayerControlViewDelegate <NSObject>

@optional
- (void)updateVideoBufferPercent:(double)arg1;
- (void)onVideoSeekActionWithDirection:(_Bool)arg1;
- (void)finderPlayerControllerViewUpdateVideoCurrentTime:(double)arg1 videoDuration:(double)arg2 maxPlayVideoTime:(double)arg3;
- (_Bool)WCFinderPlayerControlViewCanProcessGesture;
- (void)WCFinderPlayerControlViewDidTapWithTapState:(_Bool)arg1;
- (void)WCFinderPlayerControlViewProgressBarValueChange:(double)arg1 dragState:(unsigned long long)arg2 playVideo:(_Bool)arg3;
- (void)onHiddenBufferingView;
- (void)onShowBufferingView;
- (void)onGetVideoSize:(struct CGSize)arg1;
- (void)onPlayToEnd;
- (void)onVideoPause;
- (void)onVideoPlay;
@end

