//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMBaseSessionStorage, WCFinderMsgSessionInfo;

@interface WCFinderMsgSessionFindResult : NSObject
{
    _Bool _isInGreetSessionList;
    WCFinderMsgSessionInfo *_sessionInfo;
    MMBaseSessionStorage *_sessionStorage;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isInGreetSessionList; // @synthesize isInGreetSessionList=_isInGreetSessionList;
@property(retain, nonatomic) MMBaseSessionStorage *sessionStorage; // @synthesize sessionStorage=_sessionStorage;
@property(retain, nonatomic) WCFinderMsgSessionInfo *sessionInfo; // @synthesize sessionInfo=_sessionInfo;

@end

