//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCFinderAuthorityListViewModelProtocol-Protocol.h"
#import "WCFinderBatchModContactTypeTaskDelegate-Protocol.h"

@class NSMutableArray, NSString, WCFinderBatchModContactTypeTask;
@protocol WCFinderAuthorityListViewModelDelegate, WCFinderAuthorityListViewModelSearchDelegate;

@interface WCFinderOutsideFriendViewModel : NSObject <WCFinderBatchModContactTypeTaskDelegate, WCFinderAuthorityListViewModelProtocol>
{
    id <WCFinderAuthorityListViewModelDelegate> delegate;
    id <WCFinderAuthorityListViewModelSearchDelegate> searchDelegate;
    NSMutableArray *_contacts;
    WCFinderBatchModContactTypeTask *_batchContactTask;
}

+ (id)convertContact:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderBatchModContactTypeTask *batchContactTask; // @synthesize batchContactTask=_batchContactTask;
@property(retain, nonatomic) NSMutableArray *contacts; // @synthesize contacts=_contacts;
@property(nonatomic) __weak id <WCFinderAuthorityListViewModelSearchDelegate> searchDelegate; // @synthesize searchDelegate;
@property(nonatomic) __weak id <WCFinderAuthorityListViewModelDelegate> delegate; // @synthesize delegate;
- (_Bool)showSearchBar;
- (_Bool)showAddContactButton;
- (id)allContacts;
- (void)searchWithKeyword:(id)arg1;
- (_Bool)hasMoreData;
- (id)emptyTips;
- (id)guideTips;
- (void)finderBatchModContactTypeTask:(id)arg1 finishWithSuccessNames:(id)arg2 failedNames:(id)arg3 allSuccess:(_Bool)arg4;
- (void)batchConfigAddItems:(id)arg1 delItems:(id)arg2;
- (void)requestLoadFirstPageData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

