//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FinderTopicBgmInfo, NSData, NSMutableArray, NSString, WCFinderSectionInfo, WCFinderTopicInfo;
@protocol WCFinderTopicListDetailViewModelDelegate;

@interface WCFinderTopicListDetailViewModel : NSObject
{
    _Bool _isPinnedStateChanged;
    _Bool _queryContinueFlag;
    id <WCFinderTopicListDetailViewModelDelegate> _delegate;
    unsigned long long _topicType;
    unsigned long long _refreshTime;
    FinderTopicBgmInfo *_bgmInfo;
    NSMutableArray *_allSearchDataItems;
    WCFinderTopicInfo *_topicInfo;
    NSString *_latestQueryText;
    NSString *_latestRequestID;
    NSData *_lastBuffer;
    NSString *_latitude;
    NSString *_longitude;
    NSString *_refObjectid;
    long long _tabType;
    long long _innerTabType;
    long long _fromType;
    WCFinderTopicInfo *_poiTopicRecommend;
    WCFinderSectionInfo *_sectionInfo;
    unsigned long long _eventTopicId;
}

+ (unsigned long long)getReportMusicTypeWithBgmInfo:(id)arg1 topicType:(unsigned long long)arg2;
+ (id)initWithTopicType:(unsigned long long)arg1 lastBuffer:(id)arg2 latestRequestID:(id)arg3 queryText:(id)arg4 queryContinueFlag:(_Bool)arg5 dataSources:(id)arg6 latitude:(id)arg7 longitude:(id)arg8 refObjectid:(id)arg9 tabType:(long long)arg10 innerTabType:(long long)arg11 fromType:(long long)arg12 poiTopicRecommend:(id)arg13 sectionInfo:(id)arg14 bgmInfo:(id)arg15 eventTopicId:(unsigned long long)arg16;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long eventTopicId; // @synthesize eventTopicId=_eventTopicId;
@property(retain, nonatomic) WCFinderSectionInfo *sectionInfo; // @synthesize sectionInfo=_sectionInfo;
@property(retain, nonatomic) WCFinderTopicInfo *poiTopicRecommend; // @synthesize poiTopicRecommend=_poiTopicRecommend;
@property(nonatomic) long long fromType; // @synthesize fromType=_fromType;
@property(nonatomic) long long innerTabType; // @synthesize innerTabType=_innerTabType;
@property(nonatomic) long long tabType; // @synthesize tabType=_tabType;
@property(copy, nonatomic) NSString *refObjectid; // @synthesize refObjectid=_refObjectid;
@property(copy, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(copy, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(nonatomic) _Bool queryContinueFlag; // @synthesize queryContinueFlag=_queryContinueFlag;
@property(retain, nonatomic) NSData *lastBuffer; // @synthesize lastBuffer=_lastBuffer;
@property(retain, nonatomic) NSString *latestRequestID; // @synthesize latestRequestID=_latestRequestID;
@property(retain, nonatomic) NSString *latestQueryText; // @synthesize latestQueryText=_latestQueryText;
@property(nonatomic) _Bool isPinnedStateChanged; // @synthesize isPinnedStateChanged=_isPinnedStateChanged;
@property(retain, nonatomic) WCFinderTopicInfo *topicInfo; // @synthesize topicInfo=_topicInfo;
@property(retain, nonatomic) NSMutableArray *allSearchDataItems; // @synthesize allSearchDataItems=_allSearchDataItems;
@property(retain, nonatomic) FinderTopicBgmInfo *bgmInfo; // @synthesize bgmInfo=_bgmInfo;
@property(nonatomic) unsigned long long refreshTime; // @synthesize refreshTime=_refreshTime;
@property(nonatomic) unsigned long long topicType; // @synthesize topicType=_topicType;
@property(nonatomic) __weak id <WCFinderTopicListDetailViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onTopicFinderDataItemDelete:(id)arg1;
- (unsigned long long)feedViewControllerScene;
- (long long)numberOfSection;
- (long long)contentIndexOfTid:(id)arg1;
- (void)stopPreloadVideoItem:(id)arg1;
- (void)preloadVideoItems:(id)arg1;
- (void)resetSearchStatus;
- (_Bool)isNoMoreData;
- (id)latestQueryString;
- (void)onQueryNextPageDataItems;
- (void)onQueryContentWith:(id)arg1;
- (void)changeEventFeedPinToTopStateWithTid:(id)arg1 pinned:(_Bool)arg2;
- (void)removeEventFeedWithTid:(id)arg1;
- (id)contentVMWithTid:(id)arg1;
- (id)searchDataItemAtSection:(long long)arg1;
- (id)searchDataItemAtIndexPath:(id)arg1;

@end

