//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAsset, AVMutableVideoComposition, NSString, NSURL, VideoEncodeTask;

@interface WCFinderLongEncodingConfig : NSObject
{
    _Bool _hadError;
    NSURL *_assetUrl;
    AVAsset *_asset;
    AVMutableVideoComposition *_composition;
    CDUnknownBlockType _completion;
    CDUnknownBlockType _progress;
    CDUnknownBlockType _beforePostCompletion;
    NSString *_longVidoePath;
    VideoEncodeTask *_longEncodeTask;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hadError; // @synthesize hadError=_hadError;
@property(nonatomic) __weak VideoEncodeTask *longEncodeTask; // @synthesize longEncodeTask=_longEncodeTask;
@property(retain, nonatomic) NSString *longVidoePath; // @synthesize longVidoePath=_longVidoePath;
@property(copy, nonatomic) CDUnknownBlockType beforePostCompletion; // @synthesize beforePostCompletion=_beforePostCompletion;
@property(copy, nonatomic) CDUnknownBlockType progress; // @synthesize progress=_progress;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(retain, nonatomic) AVMutableVideoComposition *composition; // @synthesize composition=_composition;
@property(retain, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
@property(retain, nonatomic) NSURL *assetUrl; // @synthesize assetUrl=_assetUrl;
- (id)assetForEncoding;
- (id)onProgress:(CDUnknownBlockType)arg1;
- (id)onComplete:(CDUnknownBlockType)arg1;
- (id)composition:(id)arg1;
- (void)checkCompletion;
- (_Bool)done;
- (id)initWithUrl:(id)arg1;

@end

