//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCFinderShareListReportModel : NSObject
{
    _Bool _byPush;
    unsigned long long _enterScene;
    NSString *_sourceUser;
    NSString *_fromUsername;
    NSString *_toUsername;
    unsigned long long _commentScene;
    NSString *_reportExtraInfo;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool byPush; // @synthesize byPush=_byPush;
@property(copy, nonatomic) NSString *reportExtraInfo; // @synthesize reportExtraInfo=_reportExtraInfo;
@property(nonatomic) unsigned long long commentScene; // @synthesize commentScene=_commentScene;
@property(copy, nonatomic) NSString *toUsername; // @synthesize toUsername=_toUsername;
@property(copy, nonatomic) NSString *fromUsername; // @synthesize fromUsername=_fromUsername;
@property(copy, nonatomic) NSString *sourceUser; // @synthesize sourceUser=_sourceUser;
@property(nonatomic) unsigned long long enterScene; // @synthesize enterScene=_enterScene;
- (id)init;

@end

