//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "PBCoding-Protocol.h"
#import "WCTColumnCoding-Protocol.h"

@class FinderEventWordingInfo, NSDate, NSString, WCFinderContact;

@interface WCFinderEventModel : NSObject <PBCoding, WCTColumnCoding, NSCopying>
{
    _Bool closed;
    unsigned int participantCount;
    unsigned int feedCount;
    unsigned int maxTopCount;
    unsigned int availableFlag;
    unsigned long long eventTopicId;
    WCFinderContact *contact;
    NSString *eventName;
    NSString *description;
    NSString *coverImgUrl;
    unsigned long long fromObjectId;
    unsigned long long endTime;
    FinderEventWordingInfo *wordingInfo;
    unsigned long long _hiddenMark;
    NSDate *_endDate;
}

+ (id)fromPBEvent:(id)arg1;
+ (unsigned long long)columnTypeForWCDB;
+ (id)unarchiveWithWCTValue:(id)arg1;
+ (void)initialize;
+ (void)PBArrayAdd_wordingInfo;
+ (void)PBArrayAdd_availableFlag;
+ (void)PBArrayAdd_endTime;
+ (void)PBArrayAdd_closed;
+ (void)PBArrayAdd_maxTopCount;
+ (void)PBArrayAdd_feedCount;
+ (void)PBArrayAdd_fromObjectId;
+ (void)PBArrayAdd_coverImgUrl;
+ (void)PBArrayAdd_participantCount;
+ (void)PBArrayAdd_description;
+ (void)PBArrayAdd_eventName;
+ (void)PBArrayAdd_contact;
+ (void)PBArrayAdd_eventTopicId;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
@property(nonatomic) unsigned long long hiddenMark; // @synthesize hiddenMark=_hiddenMark;
@property(retain, nonatomic) FinderEventWordingInfo *wordingInfo; // @synthesize wordingInfo;
@property(nonatomic) unsigned int availableFlag; // @synthesize availableFlag;
@property(nonatomic) unsigned long long endTime; // @synthesize endTime;
@property(nonatomic) _Bool closed; // @synthesize closed;
@property(nonatomic) unsigned int maxTopCount; // @synthesize maxTopCount;
@property(nonatomic) unsigned int feedCount; // @synthesize feedCount;
@property(nonatomic) unsigned long long fromObjectId; // @synthesize fromObjectId;
@property(copy, nonatomic) NSString *coverImgUrl; // @synthesize coverImgUrl;
@property(nonatomic) unsigned int participantCount; // @synthesize participantCount;
@property(copy, nonatomic) NSString *description; // @synthesize description;
@property(copy, nonatomic) NSString *eventName; // @synthesize eventName;
@property(retain, nonatomic) WCFinderContact *contact; // @synthesize contact;
@property(nonatomic) unsigned long long eventTopicId; // @synthesize eventTopicId;
@property(readonly, nonatomic) _Bool hadPosted;
- (id)bindEventInfo;
- (id)convertEventInfo;
- (id)initWithEvent:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)archivedWCTValue;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

