//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, WCFinderTagListViewOptions;

@interface WCFinderTagListViewLayout : NSObject
{
    _Bool _isExpand;
    _Bool _dirty;
    WCFinderTagListViewOptions *_options;
    double _width;
    NSMutableArray *_layoutItems;
    struct CGRect _expandBtnFrame;
}

+ (id)displayTitle:(id)arg1 withLimitCharCount:(long long)arg2;
- (void).cxx_destruct;
@property(nonatomic) _Bool dirty; // @synthesize dirty=_dirty;
@property(nonatomic) struct CGRect expandBtnFrame; // @synthesize expandBtnFrame=_expandBtnFrame;
@property(retain, nonatomic) NSMutableArray *layoutItems; // @synthesize layoutItems=_layoutItems;
@property(nonatomic) _Bool isExpand; // @synthesize isExpand=_isExpand;
@property(nonatomic) double width; // @synthesize width=_width;
@property(retain, nonatomic) WCFinderTagListViewOptions *options; // @synthesize options=_options;
- (void)enumerateLayout:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) double height;
- (void)doLayout;
@property(copy, nonatomic) NSArray *items;
- (void)markDirty;
- (struct CGSize)calculateTextSize:(id)arg1;
- (id)init;

@end

