//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

#import "ILinkEventExt-Protocol.h"
#import "RichTextLayoutDelegate-Protocol.h"
#import "WCFinderFeedContentTextClickActionDelegate-Protocol.h"

@class MMUIButton, MMWebImageView, NSString, RichTextView, UIImageView, UILabel, UIView, WCFinderHeadImageView;
@protocol WCFinderEventHeaderViewDelegate;

@interface WCFinderEventHeaderView : UICollectionReusableView <WCFinderFeedContentTextClickActionDelegate, RichTextLayoutDelegate, ILinkEventExt>
{
    id <WCFinderEventHeaderViewDelegate> _delegate;
    UIView *_initiatorView;
    WCFinderHeadImageView *_avatarImageView;
    UILabel *_nicknameLabel;
    UILabel *_titleLabel;
    RichTextView *_eventDescTextview;
    MMUIButton *_rightArrowButton;
    UILabel *_timeTipsLabel;
    UIView *_miniAppView;
    MMWebImageView *_miniAppIconView;
    UILabel *_miniAppNameLabel;
    UIImageView *_rightArrowIconView;
    UILabel *_memberNumTipsLabel;
    MMUIButton *_joinButton;
}

+ (id)getDescriptionWithEventInfo:(id)arg1;
+ (double)heightWithEventInfo:(id)arg1 andViewWidth:(double)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) MMUIButton *joinButton; // @synthesize joinButton=_joinButton;
@property(retain, nonatomic) UILabel *memberNumTipsLabel; // @synthesize memberNumTipsLabel=_memberNumTipsLabel;
@property(retain, nonatomic) UIImageView *rightArrowIconView; // @synthesize rightArrowIconView=_rightArrowIconView;
@property(retain, nonatomic) UILabel *miniAppNameLabel; // @synthesize miniAppNameLabel=_miniAppNameLabel;
@property(retain, nonatomic) MMWebImageView *miniAppIconView; // @synthesize miniAppIconView=_miniAppIconView;
@property(retain, nonatomic) UIView *miniAppView; // @synthesize miniAppView=_miniAppView;
@property(retain, nonatomic) UILabel *timeTipsLabel; // @synthesize timeTipsLabel=_timeTipsLabel;
@property(retain, nonatomic) MMUIButton *rightArrowButton; // @synthesize rightArrowButton=_rightArrowButton;
@property(retain, nonatomic) RichTextView *eventDescTextview; // @synthesize eventDescTextview=_eventDescTextview;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
@property(retain, nonatomic) WCFinderHeadImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UIView *initiatorView; // @synthesize initiatorView=_initiatorView;
@property(nonatomic) __weak id <WCFinderEventHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)openEventMiniApp;
- (void)joinButtonClicked;
- (void)onClickAuthorInfoAction;
- (void)onTextClicked:(id)arg1 withRect:(struct CGRect)arg2 withView:(id)arg3;
- (double)lineWidthAtY:(double)arg1 lineIndex:(long long)arg2 richTextView:(id)arg3;
- (void)displayMoreDescription;
- (_Bool)hasShowMoreDescriptionButton;
- (void)setToDarkMode;
- (void)updateJoinButtonWithEventInfo:(id)arg1;
- (void)updateWithEventInfo:(id)arg1 showJoinButton:(_Bool)arg2;
- (void)updateLayout;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

