//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIView, WCFinderFeedContentVM, WCFinderFeedImageCDNView;

@interface WCFinderFeedSideItemView : UIButton
{
    _Bool _showHighlight;
    WCFinderFeedImageCDNView *_coverView;
    WCFinderFeedContentVM *_contentVM;
    UIView *_highlightView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool showHighlight; // @synthesize showHighlight=_showHighlight;
@property(retain, nonatomic) UIView *highlightView; // @synthesize highlightView=_highlightView;
@property(retain, nonatomic) WCFinderFeedContentVM *contentVM; // @synthesize contentVM=_contentVM;
@property(retain, nonatomic) WCFinderFeedImageCDNView *coverView; // @synthesize coverView=_coverView;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

