//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "WCFinderFeedDetailStatusViewDelegate-Protocol.h"

@class NSString, WCFinderFeedDetailStatusView;

@interface WCFinderLimitWarningViewController : MMUIViewController <WCFinderFeedDetailStatusViewDelegate>
{
    WCFinderFeedDetailStatusView *_statusView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderFeedDetailStatusView *statusView; // @synthesize statusView=_statusView;
- (void)didClickBack:(id)arg1;
- (void)onClickCloseLeftItem;
- (void)viewDidLoad;
- (_Bool)useBlackStatusbar;
- (_Bool)useTransparentNavibar;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

