//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "RingBackInfoDisplaySheetViewDelegate-Protocol.h"
#import "WCFinderDataItemExt-Protocol.h"
#import "WCFinderFeedBaseViewControllerProtocol-Protocol.h"
#import "WCFinderFeedContentVMExt-Protocol.h"
#import "WCFinderFeedListViewDataSource-Protocol.h"
#import "WCFinderFeedListViewDelegate-Protocol.h"

@class NSString, UIViewController, WCActionSheet, WCFinderCommentDetailViewController, WCFinderCreateCoordinator, WCFinderFeedContentVM, WCFinderFeedListView;
@protocol WCFinderCommentBaseViewProtocol;

@interface WCFinderMentionDetailViewController : MMUIViewController <WCFinderFeedContentVMExt, WCFinderFeedListViewDataSource, WCFinderFeedListViewDelegate, WCFinderFeedBaseViewControllerProtocol, WCFinderDataItemExt, RingBackInfoDisplaySheetViewDelegate>
{
    _Bool _shouldShowCommentList;
    _Bool _shouldShowLikeListView;
    _Bool _showFromSystemMsg;
    _Bool _hasShowTopComment;
    _Bool _isSilencePlay;
    _Bool _hasShowComment;
    _Bool _needsResumeTimelineVideo;
    WCFinderFeedContentVM *_contentVM;
    unsigned long long _scene;
    NSString *_navigationTitle;
    WCFinderFeedListView *_feedListView;
    double _startExposureTime;
    WCFinderCommentDetailViewController *_commentVC;
    WCFinderCreateCoordinator *_createCoordinator;
    UIViewController<WCFinderCommentBaseViewProtocol> *_lastCommentVC;
    double _currentVideoPlayProgress;
    WCActionSheet *_forwardActionSheet;
}

+ (_Bool)hookScrollViewDidScroll;
+ (_Bool)hookScrollViewDidEndDecelerating;
+ (_Bool)hookScrollViewDidEndDraggingWillDecelerate;
+ (_Bool)hookViewDidDisappear;
+ (_Bool)hookViewDidAppear;
+ (_Bool)hookReloadDataWrap;
+ (_Bool)hookViewDidBePoped;
+ (_Bool)hookViewDidBePushed;
+ (void)load;
- (void).cxx_destruct;
@property(retain, nonatomic) WCActionSheet *forwardActionSheet; // @synthesize forwardActionSheet=_forwardActionSheet;
@property(nonatomic) _Bool needsResumeTimelineVideo; // @synthesize needsResumeTimelineVideo=_needsResumeTimelineVideo;
@property(nonatomic) double currentVideoPlayProgress; // @synthesize currentVideoPlayProgress=_currentVideoPlayProgress;
@property(retain, nonatomic) UIViewController<WCFinderCommentBaseViewProtocol> *lastCommentVC; // @synthesize lastCommentVC=_lastCommentVC;
@property(retain, nonatomic) WCFinderCreateCoordinator *createCoordinator; // @synthesize createCoordinator=_createCoordinator;
@property(nonatomic) __weak WCFinderCommentDetailViewController *commentVC; // @synthesize commentVC=_commentVC;
@property(nonatomic) _Bool hasShowComment; // @synthesize hasShowComment=_hasShowComment;
@property(nonatomic) double startExposureTime; // @synthesize startExposureTime=_startExposureTime;
@property(nonatomic) _Bool isSilencePlay; // @synthesize isSilencePlay=_isSilencePlay;
@property(nonatomic) _Bool hasShowTopComment; // @synthesize hasShowTopComment=_hasShowTopComment;
@property(retain, nonatomic) WCFinderFeedListView *feedListView; // @synthesize feedListView=_feedListView;
@property(nonatomic) _Bool showFromSystemMsg; // @synthesize showFromSystemMsg=_showFromSystemMsg;
@property(nonatomic) _Bool shouldShowLikeListView; // @synthesize shouldShowLikeListView=_shouldShowLikeListView;
@property(copy, nonatomic) NSString *navigationTitle; // @synthesize navigationTitle=_navigationTitle;
@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;
@property(nonatomic) _Bool shouldShowCommentList; // @synthesize shouldShowCommentList=_shouldShowCommentList;
@property(retain, nonatomic) WCFinderFeedContentVM *contentVM; // @synthesize contentVM=_contentVM;
- (void)onRingToneSheetDisappear;
- (void)onFinderDataItemMentiondDisplayStatusChanged:(id)arg1;
- (unsigned long long)feedViewerScene;
- (unsigned long long)feedViewControllerScene;
- (void)onFinderDataItemPostingCommentFailBySpecialError:(id)arg1 errorCode:(int)arg2 errorMsg:(id)arg3;
- (void)deleteFeedWithContenVM:(id)arg1;
- (void)didClickToolbarDeleteAction:(id)arg1;
- (void)finderFeedListView:(id)arg1 deleteContentVM:(id)arg2;
- (void)scrollActionSheet:(id)arg1 didSelecteItem:(id)arg2;
- (void)profileViewDidClickFullTextWithTid:(id)arg1;
- (void)showDetialCommentListVCOnlyList:(_Bool)arg1;
- (void)showCommentListWithContentVM:(id)arg1 showEnterKeyBoard:(_Bool)arg2 refCommentID:(unsigned long long)arg3;
- (void)showAllLikeList;
- (void)onRefreshToolbarUI:(id)arg1;
- (void)onFinderDataItemBeSetPrivateWithTid:(id)arg1;
- (void)onFinderDataItemBeDeletedWithTid:(id)arg1;
- (void)onFeedContent:(id)arg1 likedDataChanged:(id)arg2;
- (void)onFeedContent:(id)arg1 hotCommentListChanged:(id)arg2 needAnimation:(_Bool)arg3;
- (void)finderFeedListViewDidClickScreenRotateBtn:(id)arg1;
- (_Bool)finderFeedListViewIsNoMoreData:(id)arg1;
- (id)finderFeedListViewCurrentViewController:(id)arg1;
- (_Bool)finderFeedListViewCanPreFetchData:(id)arg1;
- (unsigned long long)finderFeedListDataBeginRefreshTime:(id)arg1;
- (void)finderFeedListViewRetryFetch:(id)arg1;
- (void)finderFeedListViewFetchMoreData:(id)arg1;
- (long long)finderFeedListView:(id)arg1 sectionOfTid:(id)arg2;
- (long long)numberOfContentVMsInTableView;
- (id)finderFeedListView:(id)arg1 contentVMOfTid:(id)arg2;
- (id)finderFeedListView:(id)arg1 contentVMAtSection:(long long)arg2;
- (_Bool)finderFeedList:(id)arg1 scrollActionSheet:(id)arg2 customResponseSelecteItem:(id)arg3;
- (id)finderFeedList:(id)arg1 actionConfigureWithContentVM:(id)arg2;
- (id)specialParamsForFeedId:(id)arg1;
- (id)getListView;
- (id)feedIdByIndex:(id)arg1;
- (_Bool)isInSubScene;
- (id)feedCellViewParamModelWithContentVM:(id)arg1;
- (id)finderFeedListViewCustomTableViewParam:(id)arg1 contentVM:(id)arg2;
- (void)likeFeedContentVMAction:(id)arg1 isPrivateLike:(_Bool)arg2;
@property(readonly, nonatomic) _Bool shouldReloadDataItem;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)configureTableView;
- (_Bool)useTransparentNavibar;
- (void)dealloc;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)getGeneralListMonitorMgr;
- (_Bool)isOpenGeneralListSessionStatSwitch;
- (void)checkScrollEnd:(id)arg1;
- (void)tsScrollViewDidScroll:(id)arg1;
- (void)tsScrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)tsScrollViewDidEndDecelerating:(id)arg1;
- (void)tsViewDidDisappear:(_Bool)arg1;
- (void)tsViewDidAppear:(_Bool)arg1;
- (void)tsReloadDataWrap;
- (void)tsViewDidBePoped:(_Bool)arg1;
- (void)tsViewDidBePushed:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

