//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class MMUIButton, UIButton, UILabel, WCFinderHeadImageView;

@interface WCFinderStreamFeedLikeGuideView : UICollectionReusableView
{
    CDUnknownBlockType _actionBlock;
    CDUnknownBlockType _cancelLikeBlock;
    WCFinderHeadImageView *_avatarImageView;
    UILabel *_nickNameLabel;
    UIButton *_cancelLikeButton;
    MMUIButton *_likeActionButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak MMUIButton *likeActionButton; // @synthesize likeActionButton=_likeActionButton;
@property(retain, nonatomic) UIButton *cancelLikeButton; // @synthesize cancelLikeButton=_cancelLikeButton;
@property(retain, nonatomic) UILabel *nickNameLabel; // @synthesize nickNameLabel=_nickNameLabel;
@property(retain, nonatomic) WCFinderHeadImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(copy, nonatomic) CDUnknownBlockType cancelLikeBlock; // @synthesize cancelLikeBlock=_cancelLikeBlock;
@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
- (void)updateLikeGuideViewIsLike:(_Bool)arg1;
- (void)cancelLikeAction;
- (void)buttonAction;
- (void)setUpUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

