//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCFinderBaseCgi.h"

@class NSString;

@interface WCFinderModFeedSettingCGI : WCFinderBaseCgi
{
    _Bool _isSwitchOn;
    unsigned long long _feedID;
    long long _settingScene;
    long long _oplogScene;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failBlock;
    NSString *_userName;
    NSString *_nonceID;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *nonceID; // @synthesize nonceID=_nonceID;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(nonatomic) long long oplogScene; // @synthesize oplogScene=_oplogScene;
@property(nonatomic) long long settingScene; // @synthesize settingScene=_settingScene;
@property(nonatomic) _Bool isSwitchOn; // @synthesize isSwitchOn=_isSwitchOn;
@property(nonatomic) unsigned long long feedID; // @synthesize feedID=_feedID;
- (void)finderCgiDidFailWithError:(id)arg1 response:(id)arg2;
- (id)defaultErrorMsg:(int)arg1;
- (void)didGetResponse:(id)arg1;
- (void)createRequest;
- (id)initWithFeedID:(unsigned long long)arg1 nonceID:(id)arg2 userName:(id)arg3 isSwitchON:(_Bool)arg4 settingScene:(long long)arg5 oplogScene:(long long)arg6 successBlock:(CDUnknownBlockType)arg7 failBlock:(CDUnknownBlockType)arg8;

@end

