//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURLSessionDownloadTask;

@interface WCPaySingleDownloadTask : NSObject
{
    _Bool _isDownloading;
    NSString *_downloadUrl;
    NSURLSessionDownloadTask *_urlSessionDownloadTask;
    NSString *_filePath;
    CDUnknownBlockType _completionBlock;
    id _extraInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id extraInfo; // @synthesize extraInfo=_extraInfo;
@property(nonatomic) _Bool isDownloading; // @synthesize isDownloading=_isDownloading;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) NSURLSessionDownloadTask *urlSessionDownloadTask; // @synthesize urlSessionDownloadTask=_urlSessionDownloadTask;
@property(retain, nonatomic) NSString *downloadUrl; // @synthesize downloadUrl=_downloadUrl;
- (id)initWithDownloadTask:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;

@end

