//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableAttributedString, NSString, UITableView, UIView;

@interface WCTableViewSectionManager : NSObject
{
    _Bool _bDrawNoSeparator;
    unsigned long long _cellMode;
    UIView *_headerView;
    UIView *_footerView;
    NSString *_headerTitle;
    NSString *_footerTitle;
    NSMutableAttributedString *_attributedHeaderTitle;
    NSMutableAttributedString *_attributedFooterTitle;
    double _fHeaderHeight;
    double _fFooterHeight;
    double _fTopLineLeftInset;
    double _fBottomLineLeftInset;
    id _userInfo;
    UITableView *_tableView;
    NSMutableArray *_cells;
}

+ (id)sectionInfoFooterWithView:(id)arg1;
+ (id)sectionInfoHeaderWithView:(id)arg1;
+ (id)sectionInfoHeader:(id)arg1 Footer:(id)arg2;
+ (id)sectionInfoFooter:(id)arg1;
+ (id)sectionInfoHeader:(id)arg1;
+ (id)sectionInfoDefaut;
+ (id)sectionWithHeaderView:(id)arg1 FooterView:(id)arg2;
+ (id)sectionWithFooterView:(id)arg1;
+ (id)sectionWithHeaderView:(id)arg1;
+ (id)sectionWithHeader:(id)arg1 Footer:(id)arg2;
+ (id)sectionWithFooter:(id)arg1;
+ (id)sectionWithHeader:(id)arg1;
+ (id)defaultSection;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *cells; // @synthesize cells=_cells;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) _Bool bDrawNoSeparator; // @synthesize bDrawNoSeparator=_bDrawNoSeparator;
@property(nonatomic) double fBottomLineLeftInset; // @synthesize fBottomLineLeftInset=_fBottomLineLeftInset;
@property(nonatomic) double fTopLineLeftInset; // @synthesize fTopLineLeftInset=_fTopLineLeftInset;
@property(nonatomic) double fFooterHeight; // @synthesize fFooterHeight=_fFooterHeight;
@property(nonatomic) double fHeaderHeight; // @synthesize fHeaderHeight=_fHeaderHeight;
@property(copy, nonatomic) NSMutableAttributedString *attributedFooterTitle; // @synthesize attributedFooterTitle=_attributedFooterTitle;
@property(copy, nonatomic) NSMutableAttributedString *attributedHeaderTitle; // @synthesize attributedHeaderTitle=_attributedHeaderTitle;
@property(copy, nonatomic) NSString *footerTitle; // @synthesize footerTitle=_footerTitle;
@property(copy, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) unsigned long long cellMode; // @synthesize cellMode=_cellMode;
- (void)removeCellAt:(unsigned long long)arg1;
- (id)getCellAt:(unsigned long long)arg1;
- (id)getAllCells;
- (unsigned long long)getCellCount;
- (void)insertCell:(id)arg1 At:(unsigned int)arg2;
- (id)getFooterView;
- (id)getHeaderView;
- (id)makeViewWith:(id)arg1 attributedTitle:(id)arg2 topPading:(double)arg3 bottomPadding:(double)arg4;
- (void)didBeClickedAt:(id)arg1;
- (void)addCell:(id)arg1;
- (id)init;

@end

