//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WeVisGLDrawQuad;

@interface WeVisGLRGBA2YUVTwoPassFS : NSObject
{
    WeVisGLDrawQuad *mQuadDrawerY;
    WeVisGLDrawQuad *mQuadDrawerUV;
    _Bool _isInitialized;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isInitialized; // @synthesize isInitialized=_isInitialized;
- (void)drawUVFromRGBA:(unsigned int)arg1 transpose:(_Bool)arg2 flipX:(_Bool)arg3;
- (void)drawYFromRGBA:(unsigned int)arg1 transpose:(_Bool)arg2 flipX:(_Bool)arg3;
- (id)initWith_ITU_R_BT_601_FullRange;

@end

