//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WSReportBaseItem.h"

@class NSString;

@interface WSFTSVertEntryExposeReporter : WSReportBaseItem
{
    NSString *_sessionID;
    NSString *_exposeInfo;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *exposeInfo; // @synthesize exposeInfo=_exposeInfo;
@property(copy, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (id)reportOrderedFieldNameArr;
- (unsigned int)reportNSStringPreprocessType;
- (unsigned int)reportKvId;
- (id)initWithVertEntryArrayData:(id)arg1;

@end

