//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WWKFCommon : NSObject
{
}

+ (long long)contactUpdateMinInterval;
+ (_Bool)shouldTheWWKFFlowPushMsgVCWithMovingToMainFrame:(unsigned int)arg1;
+ (_Bool)shouldTheWWKFFlowConfirmInHalfScreen:(unsigned int)arg1;
+ (_Bool)shouldTheWWKFFlowConfirmToAddContact:(unsigned int)arg1;
+ (_Bool)shouldTheWWKFFlowPerformAddContact:(unsigned int)arg1;
+ (_Bool)shouldTheWWKFFlowPerformShowErrAlert:(int)arg1;

@end

