//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMailBaseCgi.h"

@class CommitBindXmailRequest, MMUIViewController, NSString, XMailSecondPasswordInputViewController;
@protocol XMailCommitBindCgiDelegate;

@interface XMailCommitBindCgi : XMailBaseCgi
{
    XMailSecondPasswordInputViewController *m_secPwdInputVC;
    MMUIViewController *_rootViewController;
    id <XMailCommitBindCgiDelegate> _delegate;
    NSString *_secPwdKey;
    CommitBindXmailRequest *_commitBindRequest;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CommitBindXmailRequest *commitBindRequest; // @synthesize commitBindRequest=_commitBindRequest;
@property(retain, nonatomic) NSString *secPwdKey; // @synthesize secPwdKey=_secPwdKey;
@property(nonatomic) __weak id <XMailCommitBindCgiDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak MMUIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
- (void)didFailWithError:(id)arg1 response:(id)arg2;
- (void)didGetResponse:(id)arg1;
- (_Bool)internalStartBindMailWithRequest:(id)arg1;
- (id)currentViewController;
- (_Bool)openSecPwdInputViewController;
- (_Bool)startBindMailFromWXMailWithMailAddr:(id)arg1;
- (_Bool)startBindWithSecPwd:(id)arg1;
- (void)prepareBindMailFromMailAddr:(id)arg1 ticket:(id)arg2;
- (void)prepareBindMailFromBindedQQ;
- (id)init;

@end

