//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface YtRawImgData_OC : JSONModel
{
    int _x;
    int _y;
    NSString *_image;
    long long _capture_time;
    NSString *_checksum;
}

- (void).cxx_destruct;
@property(nonatomic) int y; // @synthesize y=_y;
@property(nonatomic) int x; // @synthesize x=_x;
@property(retain, nonatomic) NSString *checksum; // @synthesize checksum=_checksum;
@property(nonatomic) long long capture_time; // @synthesize capture_time=_capture_time;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;

@end

