//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebKit/WKWebView.h>

#import "WKNavigationDelegate-Protocol.h"
#import "WKScriptMessageHandler-Protocol.h"
#import "WKScriptMessageHandlerWithReply-Protocol.h"
#import "WKUIDelegate-Protocol.h"
#import "YYWebViewInterface-Protocol.h"

@class NSMutableArray, NSString, NSURLRequest, UIScrollView, YYWKWebViewScriptMessageHandler, YYWKWebViewScriptMessageReplyHandler;
@protocol YYWebViewDelegate;

@interface YYBaseWebView : WKWebView <WKScriptMessageHandlerWithReply, WKNavigationDelegate, WKUIDelegate, WKScriptMessageHandler, YYWebViewInterface>
{
    _Bool disablePreviewElement;
    _Bool _bDisablePopup;
    id <YYWebViewDelegate> wvDelegate;
    YYWKWebViewScriptMessageHandler *_scriptMessageHandler;
    YYWKWebViewScriptMessageReplyHandler *_scriptMessageReplyHandler;
    NSMutableArray *_customScriptHandlerArray;
}

+ (id)processPool;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *customScriptHandlerArray; // @synthesize customScriptHandlerArray=_customScriptHandlerArray;
@property(retain, nonatomic) YYWKWebViewScriptMessageReplyHandler *scriptMessageReplyHandler; // @synthesize scriptMessageReplyHandler=_scriptMessageReplyHandler;
@property(retain, nonatomic) YYWKWebViewScriptMessageHandler *scriptMessageHandler; // @synthesize scriptMessageHandler=_scriptMessageHandler;
@property(nonatomic) _Bool bDisablePopup; // @synthesize bDisablePopup=_bDisablePopup;
@property(nonatomic) _Bool disablePreviewElement; // @synthesize disablePreviewElement;
@property(nonatomic) __weak id <YYWebViewDelegate> wvDelegate; // @synthesize wvDelegate;
- (id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4;
- (id)reload;
- (void)LoadHTMLString:(id)arg1 baseURL:(id)arg2;
- (void)LoadRequest:(id)arg1;
- (void)addScriptMessageHandlerName:(id)arg1;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (_Bool)webView:(id)arg1 shouldPreviewElement:(id)arg2;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (long long)wkNavigationTypeToYYWebViewNavigationType:(long long)arg1;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)makeAllowDecision:(CDUnknownBlockType)arg1;
- (id)currentProcessPool;
- (void)enableJavaScriptPopup:(_Bool)arg1;
- (void)evaluateJavaScriptFromString:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSURLRequest *request;
- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)configurationWillCreate:(id)arg1;
- (id)defaultConfigurationWithPreInjectJSStr:(id)arg1 hookJSStr:(id)arg2 arrCookies:(id)arg3;

// Remaining properties
@property(nonatomic) _Bool allowsBackForwardNavigationGestures;
@property(readonly, nonatomic, getter=canGoBack) _Bool canGoBack;
@property(readonly, nonatomic, getter=canGoForward) _Bool canGoForward;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=isLoading) _Bool loading;
@property(readonly, nonatomic) UIScrollView *scrollView;
@property(readonly) Class superclass;

@end

